/// Comprehensive Multilingual dictionary supporting 10 languages with exact RTL/LTR support.
class AppStrings {
  static bool isRtl(String lang) {
    return lang == 'fa' || lang == 'ar' || lang == 'ckb';
  }

  static String getArrow(String lang) {
    return isRtl(lang) ? '←' : '→';
  }

  static final Map<String, Map<String, String>> _translations = {
    // 1. FARSI / PERSIAN (فارسی - RTL)
    'fa': {
      'my_alerts': 'هشدارهای من',
      'history': 'تاریخچه',
      'settings': 'تنظیمات',
      'smart_alerts_desc': 'بررسی هوشمند بر اساس زمان‌بندی دلخواه',
      'new_alert': 'افزودن هشدار جدید',
      'last_checked_price': 'آخرین قیمت بررسی‌شده:',
      'check_now': 'بررسی آنی',
      'baseline': 'مبنا',
      'rearm': 'فعال‌سازی مجدد',
      'theme_and_colors': 'پوسته و رنگ‌بندی',
      'theme_dark_green': 'زمردی تاریک (پیش‌فرض)',
      'theme_light_green': 'زمردی روشن',
      'theme_dark_orange': 'نارنجی تاریک',
      'theme_light_orange': 'نارنجی روشن',
      'theme_dark_purple_blue': 'بنفش آبی تاریک',
      'theme_light_purple_blue': 'بنفش آبی روشن',
      'tts_voice_title': 'اعلام صوتی هوشمند (Text to Speech)',
      'tts_voice_desc': 'هنگام وقوع هشدار، نام ارز و نرخ با صدای طبیعی خوانده می‌شود',
      'tts_test_button': '🗣️ تست خوانش صوتی',
      'home_widget_title': 'ویجت زنده صفحه اصلی',
      'home_widget_desc': 'رصد لحظه‌ای آلارم‌ها و فاصله تا هدف روی صفحه اصلی',
      'select_language': 'زبان برنامه',
      'sound_and_vibrate': 'صدا و لرزش (Sound & Haptics)',
      'sound_alert': 'صدای هشدار و آلارم',
      'vibrate_alert': 'ویبره هنگام هشدار',
      'test_sound_button': '🔔 تست صدای آلارم و نوتیفیکیشن',
      'backup_and_restore': 'پشتیبان‌گیری و بازیابی',
      'export_backup': 'پشتیبان‌گیری از هشدارها (Export)',
      'restore_backup': 'بازیابی هشدارها (Restore)',
      'clear_history': 'پاک‌سازی تاریخچه اعلان‌ها',
      'battery_settings': 'بهینه‌سازی باتری در پس‌زمینه (Android)',
      'battery_active': 'معاف از بهینه‌سازی باتری (اجرای مطمئن)',
      'battery_request': 'درخواست معافیت باتری',
      'test_alert_title': 'تست سامانه هشدار Alarmer',
      'test_alert_body': 'صدا و اعلان تستی با موفقیت روی دستگاه شما به صدا درآمد!',
      'backup_copied': '✅ پشتیبان‌گیری انجام شد و در کلیپ‌بورد کپی گردید.',
      'restore_success': 'هشدارها با موفقیت بازیابی شدند.',
      'exchange': 'صرافی',
      'pair': 'جفت‌ارز',
      'create_alert_title': 'ایجاد هشدار هوشمند',
      'frequency': 'دوره بررسی',
      'seconds': 'ثانیه',
      'minutes': 'دقیقه',
      'hours': 'ساعت',
      'empty_alerts_title': 'هنوز هشداری تنظیم نشده است',
      'empty_alerts_desc': 'می‌توانید برای هر رمزارز، اوراق قرضه آمریکا یا سهام جهانی هشدار تنظیم کنید.',
      'create_first_alert': 'ایجاد اولین هشدار هوشمند',
      'choose_market_step': 'گام نخست: انتخاب نوع بازار',
      'choose_market_title': 'مایلید برای کدام بازار هشدار تنظیم کنید؟',
      'choose_market_desc': 'نوع بازار و دارایی مورد نظر خود را برای پایش دقیق قیمت انتخاب نمایید.',
      'crypto_market_title': '⚡ بازار رمزارزها (کریپتو)',
      'crypto_market_badge': 'بیش از ۴۰ صرافی معتبر',
      'crypto_market_desc': 'بیش از ۴۰ صرافی معتبر بین‌المللی و ایرانی با چیپ‌های فیلتر، استخراج جفت‌ارزها و دکمه بروزرسانی',
      'crypto_market_cta': 'ورود به بخش صرافی‌های کریپتو ←',
      'macro_market_title': '🏛️ سهام، اوراق قرضه آمریکا و فارکس',
      'macro_market_badge': 'وال استریت و اقتصاد کلان',
      'macro_market_desc': 'اوراق قرضه ۱۰ ساله آمریکا (US10Y)، جفت‌ارزهای فارکس، سهام‌های نزدک/نیویورک، طلا و شاخص‌ها',
      'macro_market_cta': 'ورود به بازارهای جهانی ←',
      'search_exchange_hint': 'جستجوی صرافی (Binance, Nobitex, Wallex, KuCoin)...',
      'search_crypto_hint': 'جستجوی رمزارز (BTC, ETH, SOL, POL, DOGE)...',
      'search_macro_hint': 'جستجوی نماد (US10Y, EUR/USD, NVDA, طلا)...',
      'refresh_list': 'بروزرسانی لیست',
      'select_cta': 'انتخاب ←',
      'selected_asset': 'دارایی انتخاب‌شده:',
      'auto_check_schedule': '۱. زمان‌بندی بررسی خودکار:',
      'unit_count': 'تعداد واحد',
      'time_unit': 'واحد زمان',
      'condition_type': '۲. نوع شرط هشدار:',
      'percent_change': 'درصد تغییر (%)',
      'price_target': 'قیمت هدف (\$)',
      'price_direction': 'جهت نوسان قیمت:',
      'both_ways': '± هر دو طرف',
      'above_only': '▲ فقط افزایش',
      'below_only': '▼ فقط کاهش',
      'target_price_label': 'قیمت هدف (دلار)',
      'percent_label': 'درصد نوسان مد نظر (%)',
      'save_alert_cta': 'ذخیره و شروع بررسی هشدار',
      'just_now': 'همین الان',
      'seconds_ago': 'ثانیه قبل',
      'minutes_ago': 'دقیقه قبل',
      'hours_ago': 'ساعت قبل',
      'days_ago': 'روز قبل',
      'every': 'هر',
      'cancel': 'انصراف',
      'confirm': 'تأیید',
      'restore_dialog_hint': 'متن فایل JSON پشتیبان‌گیری شده را در کادر زیر جای‌گذاری (Paste) کنید:',
      'restore_dialog_btn': 'تأیید و بازیابی',
      'clear_history_confirm': 'آیا از پاک کردن تمامی اعلان‌ها و رکوردهای ثبت‌شده اطمینان دارید؟',
      'clear_history_btn': 'پاک‌سازی',
      'clear_history_success': 'تمامی لاگ‌های تاریخچه اعلان‌ها پاک شدند.',
      'battery_exempt_active': 'فعال (هشدارها سر وقت اجرا می‌شوند)',
      'battery_exempt_inactive': 'غیرفعال (ممکن است سیستم هشدار را متوقف کند)',
      'battery_exempt_title': 'معافیت از محدودیت باتری',
      'battery_exempt_success': 'معافیت از بهینه‌سازی باتری با موفقیت ثبت شد.',
      'export_backup_desc': 'خروجی گرفتن از تمام هشدارهای فعال در قالب فایل JSON',
      'restore_backup_desc': 'وارد کردن و بازگردانی هشدارها از فایل یا متن JSON',
      'clear_history_desc': 'حذف تمامی گزارش‌ها و لاگ‌های ثبت‌شده',
      'filter_all': 'همه اعلان‌ها',
      'filter_triggered': 'فعال‌شده‌ها',
      'filter_suppressed': 'محدودشده‌ها',
      'no_history_title': 'تاریخچه‌ای ثبت نشده است',
      'no_history_desc': 'هنگامی که هشدارهای قیمتی شما اجرا شوند، گزارش وقایع در اینجا نمایش داده می‌شود.',
      'check_price_done': 'بررسی قیمت انجام شد: ',
      'alert_deleted_msg': 'هشدار حذف شد: ',
      'undo_action': 'بازگردانی',
      'target_price_required': 'لطفاً قیمت هدف را وارد کنید',
      'all_symbols': 'همه نمادها',
      'us_bonds': '🏛️ اوراق قرضه آمریکا',
      'forex_pairs': '💱 فارکس (ارزها)',
      'gold_metals': '🥇 طلا و فلزات',
      'wallstreet_stocks': '📈 سهام وال‌استریت',
      'global_indices': '🌐 شاخص‌های جهانی',
      'price_cross_above': 'عبور به بالاتر از (▲)',
      'price_cross_below': 'سقوط به پایین‌تر از (▼)',
      'price_cross_direction': 'جهت عبور قیمت:',
      'above_target': '▲ بالاتر از هدف',
      'below_target': '▼ پایین‌تر از هدف',
      'price_fluctuation': 'نوسان قیمت:',
      'price_surge': 'افزایش قیمت:',
      'price_drop': 'کاهش قیمت:',
      'target_price_summary': 'قیمت هدف:',
      'price_delta_summary': 'تغییر دلاری:',
      'volume_surge_summary': 'جهش حجم معاملات:',
      'interval_prefix': '⏱️ بررسی قیمت هر ',
      'interval_suffix': ' یک‌بار در پس‌زمینه انجام خواهد شد.',
      'offline_error': 'عدم دسترسی به اینترنت. آخرین قیمت واقعی نگه‌داری می‌شود.',
      'offline_badge': 'آفلاین (قیمت قبلی)',
      'edit_alert_title': 'ویرایش تنظیمات هشدار',
      'save_changes_cta': 'ذخیره تغییرات هشدار',
      'sound_and_vibrate_section': '۳. تنظیمات صدا، ویبره و متن پیام اعلان:',
      'sound_and_vibrate_sub': 'امکان شخصی‌سازی اعلان برای این شرط خاص',
      'custom_note_title': 'متن / یادداشت اختصاصی هنگام آلارم',
      'custom_note_hint': 'مثلاً: تارگت ۱ رسید - ۵۰٪ سیو سود کن!',
      'alarm_sound_title': 'آهنگ زنگ این آلارم',
      'change_sound_btn': 'تغییر صدا',
      'play_sound_label': 'پخش صدا',
      'vibrate_phone_label': 'ویبره گوشی',
      'select_alarm_sound': 'انتخاب آهنگ زنگ آلارم',
      'confirm_sound_btn': 'تأیید و ذخیره صدا',
      'live_market_price': 'قیمت لحظه‌ای بازار:',
      'fetching_live_price': 'در حال دریافت قیمت زنده...',
      'live_price_unavailable': 'عدم دسترسی به قیمت زنده',
      'manual_monitoring': 'پایش دستی',
      'symbol_not_found': 'نماد مورد نظر یافت نشد',
      'triggers_count': 'دفعات اجرا:',
      'last_trigger': 'آخرین:',
      'trigger_price_label': 'قیمت فعال‌سازی:',
      'duplicate_action': 'تکثیر هشدار',
      'edit_action': 'ویرایش',
      'delete_action': 'حذف',
      'cooldown_active': 'زمان استراحت (Cooldown)',
      'alarm_volume_label': 'بلندی صدای آلارم',
      'selected_sound_label': 'صدای زنگ آلارم انتخابی',
      'sound_alarm_siren_title': '🚨 آژیر اضطراری نوسان (Siren)',
      'sound_radar_pulse_title': '📡 پالس رادار و تارگت (Radar)',
      'sound_cyber_chime_title': '⚡ چایم سایبری بایننس (Cyber)',
      'sound_crystal_ping_title': '💎 پینگ کریستالی شفاف (Crystal)',
      'sound_bullish_rise_title': '📈 صعود شارپ و بولیش (Ascend)',
      'sound_coin_drop_title': '🪙 صدای تراکنش و سکه (Coin)',
      'sound_alert_horn_title': '🎺 شیپور اعلام خطر (Horn)',
      'sound_classic_beep_title': '📟 بیپ کلاسیک صرافی (Beep)',
      'cat_all_exchanges': 'همه صرافی‌های کریپتو',
      'cat_tier1': 'جهانی رتبه یک (Tier-1)',
      'cat_middle_east': 'ایران و خاورمیانه',
      'cat_asia': 'آسیا و شرق دور',
      'cat_europe': 'اروپا',
      'cat_americas': 'آمریکا و سایر',
      'cat_aggregator': 'مراجع و شاخص‌های تجمیع',
      'retry_btn': 'تلاش مجدد',
      'date_today': 'امروز',
      'date_yesterday': 'دیروز',
      'rule_copied': 'کد JSON هشدار در کلیپ‌بورد کپی شد',
      'format_error_json': 'خطای قالب در فایل پشتیبان JSON.',
      'rearm_now_btn': 'فعال‌سازی آنی',
      'rearm_dialog_title': 'فعال‌سازی مجدد هشدار؟',
      'rearm_dialog_body': 'با این کار، دوره استراحت فوراً پایان یافته و پایش زنده از سر گرفته می‌شود.',
      'alert_rule_duplicated': 'هشدار با موفقیت تکثیر شد',
      'export_rule_action': 'خروجی گرفتن (JSON)',
      'popular_cryptos': 'رمزارزهای محبوب:',
    },

    // 2. ENGLISH (English - LTR)
    'en': {
      'my_alerts': 'My Alerts',
      'history': 'History',
      'settings': 'Settings',
      'smart_alerts_desc': 'Intelligent monitoring based on custom schedule',
      'new_alert': 'Add New Alert',
      'last_checked_price': 'Last Checked Price:',
      'check_now': 'Check Now',
      'baseline': 'Base',
      'rearm': 'Re-arm Alert',
      'theme_and_colors': 'Theme & Color Scheme',
      'theme_dark_green': 'Dark Emerald (Default)',
      'theme_light_green': 'Light Emerald',
      'theme_dark_orange': 'Dark Orange',
      'theme_light_orange': 'Light Orange',
      'theme_dark_purple_blue': 'Dark Purple Blue',
      'theme_light_purple_blue': 'Light Purple Blue',
      'tts_voice_title': 'Smart Voice Announcer (Text-to-Speech)',
      'tts_voice_desc': 'Vocalizes the currency and price with natural speech upon alert trigger',
      'tts_test_button': '🗣️ Test Voice Speech',
      'home_widget_title': 'Live Home Screen Widget',
      'home_widget_desc': 'Real-time alert monitoring & target proximity on home screen',
      'select_language': 'Language',
      'sound_and_vibrate': 'Sound & Haptics',
      'sound_alert': 'Alarm Sound',
      'vibrate_alert': 'Vibration Alert',
      'test_sound_button': '🔔 Test Alarm & Notification',
      'backup_and_restore': 'Backup & Restore',
      'export_backup': 'Export Alerts Backup (JSON)',
      'restore_backup': 'Restore Alerts (JSON)',
      'clear_history': 'Clear Notification History',
      'battery_settings': 'Battery Optimization (Android)',
      'battery_active': 'Exempt from battery optimization (Reliable)',
      'battery_request': 'Request Exemption',
      'test_alert_title': 'Alarmer Test Notification',
      'test_alert_body': 'Sound and notification successfully triggered on your device!',
      'backup_copied': '✅ Backup copied to clipboard successfully.',
      'restore_success': 'Alerts restored successfully.',
      'exchange': 'Exchange',
      'pair': 'Market Pair',
      'create_alert_title': 'Create Smart Alert',
      'frequency': 'Frequency',
      'seconds': 'Sec',
      'minutes': 'Min',
      'hours': 'Hours',
      'empty_alerts_title': 'No Alerts Configured Yet',
      'empty_alerts_desc': 'You can set percent change or price target alerts for any crypto, US bond, or global stock.',
      'create_first_alert': 'Create First Smart Alert',
      'choose_market_step': 'Step 1: Choose Market Type',
      'choose_market_title': 'Which market would you like to track?',
      'choose_market_desc': 'Select your desired market type and asset to accurately monitor prices.',
      'crypto_market_title': '⚡ Crypto Market (Cryptocurrencies)',
      'crypto_market_badge': '40+ Verified Exchanges',
      'crypto_market_desc': 'Over 40 top international and verified exchanges with category filters and pair auto-discovery.',
      'crypto_market_cta': 'Enter Crypto Exchanges →',
      'macro_market_title': '🏛️ US Stocks, Treasury Bonds & Forex',
      'macro_market_badge': 'Wall Street & Macro Economy',
      'macro_market_desc': 'US 10-Year Yields (US10Y), Forex pairs, Nasdaq/NYSE equities, Gold & Global Indices.',
      'macro_market_cta': 'Enter Global Markets →',
      'search_exchange_hint': 'Search exchange (Binance, Nobitex, Wallex, KuCoin)...',
      'search_crypto_hint': 'Search crypto (BTC, ETH, SOL, POL, DOGE)...',
      'search_macro_hint': 'Search symbol (US10Y, EUR/USD, NVDA, Gold)...',
      'refresh_list': 'Refresh Pairs',
      'select_cta': 'Select →',
      'selected_asset': 'Selected Asset:',
      'auto_check_schedule': '1. Automated Check Schedule:',
      'unit_count': 'Interval Value',
      'time_unit': 'Time Unit',
      'condition_type': '2. Alert Condition Type:',
      'percent_change': 'Percent Change (%)',
      'price_target': 'Price Target (\$)',
      'price_direction': 'Price Direction:',
      'both_ways': '± Both Ways',
      'above_only': '▲ Above Only',
      'below_only': '▼ Below Only',
      'target_price_label': 'Target Price (\$)',
      'percent_label': 'Target Percentage (%)',
      'save_alert_cta': 'Save and Start Monitoring',
      'just_now': 'Just now',
      'seconds_ago': 's ago',
      'minutes_ago': 'm ago',
      'hours_ago': 'h ago',
      'days_ago': 'd ago',
      'every': 'Every',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'restore_dialog_hint': 'Paste your exported JSON backup text into the box below:',
      'restore_dialog_btn': 'Confirm & Restore',
      'clear_history_confirm': 'Are you sure you want to clear all notification history logs?',
      'clear_history_btn': 'Clear All',
      'clear_history_success': 'All notification history logs have been cleared.',
      'battery_exempt_active': 'Active (Alerts run precisely on schedule)',
      'battery_exempt_inactive': 'Inactive (Background tasks may be paused by OS)',
      'battery_exempt_title': 'Battery Optimization Exemption',
      'battery_exempt_success': 'Battery exemption granted successfully.',
      'export_backup_desc': 'Export all active alerts to a JSON file or clipboard',
      'restore_backup_desc': 'Import and restore alerts from a JSON file or text',
      'clear_history_desc': 'Delete all stored logs and notification history',
      'filter_all': 'All Logs',
      'filter_triggered': 'Triggered',
      'filter_suppressed': 'Suppressed',
      'no_history_title': 'No History Logged Yet',
      'no_history_desc': 'When your price alert conditions are met, events will be recorded here.',
      'check_price_done': 'Price check completed: ',
      'alert_deleted_msg': 'Alert deleted: ',
      'undo_action': 'Undo',
      'target_price_required': 'Please enter a target price',
      'all_symbols': 'All Assets',
      'us_bonds': '🏛️ US Treasury Bonds',
      'forex_pairs': '💱 Forex Pairs',
      'gold_metals': '🥇 Gold & Metals',
      'wallstreet_stocks': '📈 Wall Street Equities',
      'global_indices': '🌐 Global Indices',
      'price_cross_above': 'Cross above (▲)',
      'price_cross_below': 'Drop below (▼)',
      'price_cross_direction': 'Crossing Direction:',
      'above_target': '▲ Above Target',
      'below_target': '▼ Below Target',
      'price_fluctuation': 'Price change:',
      'price_surge': 'Price increase:',
      'price_drop': 'Price drop:',
      'target_price_summary': 'Target price:',
      'price_delta_summary': 'Price delta:',
      'volume_surge_summary': 'Volume surge:',
      'interval_prefix': '⏱️ Automated price check runs every ',
      'interval_suffix': ' in background.',
      'offline_error': 'No internet connection. Keeping last recorded authentic price.',
      'offline_badge': 'Offline (Last Price)',
      'edit_alert_title': 'Edit Price Alert',
      'save_changes_cta': 'Save Alert Changes',
      'sound_and_vibrate_section': '3. Sound, Vibration & Note Settings:',
      'sound_and_vibrate_sub': 'Customize notification behavior for this condition',
      'custom_note_title': 'Custom Notification Message / Note',
      'custom_note_hint': 'e.g., Target 1 reached - Take 50% profit!',
      'alarm_sound_title': 'Alert Ringtone',
      'change_sound_btn': 'Change Sound',
      'play_sound_label': 'Play Sound',
      'vibrate_phone_label': 'Vibrate Phone',
      'select_alarm_sound': 'Select Alert Sound',
      'confirm_sound_btn': 'Confirm & Save Sound',
      'live_market_price': 'Live Market Price:',
      'fetching_live_price': 'Fetching live price...',
      'live_price_unavailable': 'Live price unavailable',
      'manual_monitoring': 'Manual Monitoring',
      'symbol_not_found': 'No matching symbols found',
      'triggers_count': 'Triggers:',
      'last_trigger': 'Last:',
      'trigger_price_label': 'Trigger Price:',
      'duplicate_action': 'Duplicate',
      'edit_action': 'Edit',
      'delete_action': 'Delete',
      'cooldown_active': 'Cooldown Active',
      'alarm_volume_label': 'Alarm Volume',
      'selected_sound_label': 'Selected Alarm Sound',
      'sound_alarm_siren_title': '🚨 Emergency Siren (Siren)',
      'sound_radar_pulse_title': '📡 Radar Target Pulse (Radar)',
      'sound_cyber_chime_title': '⚡ Cyber Trading Chime (Cyber)',
      'sound_crystal_ping_title': '💎 Crystal Clear Ping (Crystal)',
      'sound_bullish_rise_title': '📈 Bullish Surge (Ascend)',
      'sound_coin_drop_title': '🪙 Digital Coin Drop (Coin)',
      'sound_alert_horn_title': '🎺 Market Warning Horn (Horn)',
      'sound_classic_beep_title': '📟 Classic Exchange Beep (Beep)',
      'cat_all_exchanges': 'All Crypto Exchanges',
      'cat_tier1': 'Tier-1 Global',
      'cat_middle_east': 'Middle East & Iran',
      'cat_asia': 'Asia & Far East',
      'cat_europe': 'Europe',
      'cat_americas': 'Americas & Others',
      'cat_aggregator': 'Aggregators & Indices',
      'retry_btn': 'Retry',
      'date_today': 'Today',
      'date_yesterday': 'Yesterday',
      'rule_copied': 'Rule JSON copied to clipboard',
      'format_error_json': 'Format error in JSON backup file.',
      'rearm_now_btn': 'Re-arm Now',
      'rearm_dialog_title': 'Re-arm Alert Now?',
      'rearm_dialog_body': 'This will immediately end the cooldown period and re-enable real-time triggers.',
      'alert_rule_duplicated': 'Alert rule duplicated successfully',
      'export_rule_action': 'Export Rule (JSON)',
      'popular_cryptos': 'Popular Cryptocurrencies:',
    },

    // 3. KURDISH SORANI (کوردی سۆرانی - RTL)
    'ckb': {
      'my_alerts': 'ئاگادارییەکانی من',
      'history': 'مێژوو',
      'settings': 'ڕێکخستنەکان',
      'smart_alerts_desc': 'چاودێری زیرەک بەپێی کاتی دیاریکراو',
      'new_alert': 'زیادکردنی ئاگاداری',
      'last_checked_price': 'دواین نرخی پشکنراو:',
      'check_now': 'پشکنینی خێرا',
      'baseline': 'بنەما',
      'rearm': 'چالاککردنەوە',
      'theme_and_colors': 'ڕووکار و ڕەنگ',
      'theme_dark_green': 'سەوزی تاریک (بنەڕەت)',
      'theme_light_green': 'سەوزی ڕووناک',
      'theme_dark_orange': 'پڕتەقاڵی تاریک',
      'theme_light_orange': 'پڕتەقاڵی ڕووناک',
      'theme_dark_purple_blue': 'مۆری شینی تاریک',
      'theme_light_purple_blue': 'مۆری شینی ڕووناک',
      'tts_voice_title': 'خوێندنەوەی دەنگی زیرەک (Text-to-Speech)',
      'tts_voice_desc': 'لە کاتی ئاگادارکردنەوە، ناوی دراو و نرخەکە دەخوێنرێتەوە',
      'tts_test_button': '🗣️ تاقیکردنەوەی دەنگ',
      'home_widget_title': 'ویجێتی زیندووی سەر شاشە',
      'home_widget_desc': 'چاودێری ڕاستەوخۆی ئاگادارکەرەوەکان لەسەر شاشەی سەرەکی',
      'select_language': 'زمانی بەرنامە',
      'sound_and_vibrate': 'دەنگ و لەرزین',
      'sound_alert': 'دەنگی ئاگادارکردنەوە',
      'vibrate_alert': 'لەرزین لە کاتی ئاگاداری',
      'test_sound_button': '🔔 تاقیکردنەوەی دەنگ و ئاگاداری',
      'backup_and_restore': 'هەڵگرتنەوە و گێڕانەوە',
      'export_backup': 'هەڵگرتنی پاڵپشت (Export JSON)',
      'restore_backup': 'گێڕانەوەی ئاگادارییەکان (Restore)',
      'clear_history': 'سڕینەوەی مێژووی ئاگادارییەکان',
      'battery_settings': 'ڕێکخستنی پاتری (Android)',
      'battery_active': 'بەخشراو لە سنوورداری پاتری',
      'battery_request': 'داواکردنی بەخشین',
      'test_alert_title': 'تاقیکردنەوەی ئاگاداری',
      'test_alert_body': 'دەنگ و ئاگاداری بە سەرکەوتوویی تاقیکرایەوە!',
      'backup_copied': '✅ پاڵپشت لە کلیپبۆرد کۆپیکرا.',
      'restore_success': 'ئاگادارییەکان گەڕێنرانەوە.',
      'exchange': 'بۆرسە',
      'pair': 'جووتە دراو',
      'create_alert_title': 'دروستکردنی ئاگاداری نوێ',
      'frequency': 'ماوەی پشکنین',
      'seconds': 'چرکە',
      'minutes': 'خولەک',
      'hours': 'کاتژمێر',
      'empty_alerts_title': 'هیچ ئاگادارییەک دانەنراوە',
      'empty_alerts_desc': 'دەتوانیت بۆ کریپتۆ، بۆندەکانی ئەمریکا یان پشکەکان ئاگاداری دابنێیت.',
      'create_first_alert': 'یەکەم ئاگاداری دروست بکە',
      'choose_market_step': 'هەنگاوی یەکەم: هەڵبژاردنی بازاڕ',
      'choose_market_title': 'دەتەوێت بۆ کام بازاڕ ئاگاداری دابنێیت؟',
      'choose_market_desc': 'جۆری بازاڕ و سەرمایەی مەبەست هەڵبژێرە.',
      'crypto_market_title': '⚡ بازاڕی دراوی کریپتۆ',
      'crypto_market_badge': 'زیاتر لە ٤٠ بۆرسەی باوەڕپێکراو',
      'crypto_market_desc': 'زیاتر لە ٤٠ بۆرسەی نێودەوڵەتی بە فلتەری جۆراوجۆر و جفتە دراوەکانەوە.',
      'crypto_market_cta': 'چوونە ناو بۆرسەکانی کریپتۆ ←',
      'macro_market_title': '🏛️ پشکەکان، بۆندەکانی ئەمریکا و فۆرێکس',
      'macro_market_badge': 'واڵ ستریت و ئابووری جیهانی',
      'macro_market_desc': 'بۆندی ۱۰ ساڵەی ئەمریکا، فۆرێکس، پشکەکانی نەزداک و زێڕ.',
      'macro_market_cta': 'چوونە ناو بازاڕە جیهانییەکان ←',
      'search_exchange_hint': 'گەڕان بۆ بۆرسە (Binance, Nobitex, Wallex)...',
      'search_crypto_hint': 'گەڕان بۆ کریپتۆ (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'گەڕان بۆ هێما (US10Y, EUR/USD, زێڕ)...',
      'refresh_list': 'نوێکردنەوەی لیست',
      'select_cta': 'هەڵبژاردن ←',
      'selected_asset': 'سەرمایەی هەڵبژێردراو:',
      'auto_check_schedule': '١. کاتی پشکنینی خۆکار:',
      'unit_count': 'ژمارە',
      'time_unit': 'یەکەی کات',
      'condition_type': '٢. مەرجی ئاگاداری:',
      'percent_change': 'ڕێژەی گۆڕان (%)',
      'price_target': 'نرخی مەبەست (\$)',
      'price_direction': 'ئاراستەی نرخ:',
      'both_ways': '± هەردوو لا',
      'above_only': '▲ تەنها بەرزبوونەوە',
      'below_only': '▼ تەنها دابەزین',
      'target_price_label': 'نرخی مەبەست (دۆلار)',
      'percent_label': 'ڕێژەی سەدی (%)',
      'save_alert_cta': 'پاشەکەوت و دەستپێکردنی چاودێری',
      'just_now': 'ئێستا',
      'seconds_ago': 'چرکە لەمەوبەر',
      'minutes_ago': 'خولەک لەمەوبەر',
      'hours_ago': 'کاتژمێر لەمەوبەر',
      'days_ago': 'ڕۆژ لەمەوبەر',
      'every': 'هەموو',
      'cancel': 'پاشگەزبوونەوە',
      'confirm': 'پەسەندکردن',
      'restore_dialog_hint': 'دەقی فایلی JSON لەم خانەیەدا دابنێ:',
      'restore_dialog_btn': 'پەسەند و گێڕانەوە',
      'clear_history_confirm': 'ئایا دڵنیایت لە سڕینەوەی هەموو مێژووەکە؟',
      'clear_history_btn': 'سڕینەوە',
      'clear_history_success': 'هەموو مێژووەکە سڕایەوە.',
      'battery_exempt_active': 'چالاکە',
      'battery_exempt_inactive': 'ناچالاکە',
      'battery_exempt_title': 'بەخشینی پاتری',
      'battery_exempt_success': 'بەخشینی پاتری بە سەرکەوتوویی ئەنجامدرا.',
      'export_backup_desc': 'دەرهێنانی هەموو ئاگادارییەکان وەک فایلی JSON',
      'restore_backup_desc': 'گێڕانەوەی ئاگادارییەکان لە فایلی JSON',
      'clear_history_desc': 'سڕینەوەی هەموو مێژوو و ئاگادارییە تۆمارکراوەکان',
      'filter_all': 'هەمووی',
      'filter_triggered': 'لێدراوەکان',
      'filter_suppressed': 'ڕاگیراوەکان',
      'no_history_title': 'هیچ مێژوویەک نییە',
      'no_history_desc': 'کاتێک ئاگادارییەکان کار دەکەن، ڕاپۆرتەکان لێرە دەردەکەون.',
      'check_price_done': 'پشکنینی نرخ ئەنجامدرا: ',
      'alert_deleted_msg': 'ئاگاداری سڕایەوە: ',
      'undo_action': 'گێڕانەوە',
      'target_price_required': 'تکایە نرخی مەبەست بنووسە',
      'all_symbols': 'هەموو نمادەکان',
      'us_bonds': '🏛️ بۆندەکانی ئەمریکا',
      'forex_pairs': '💱 فۆرێکس',
      'gold_metals': '🥇 زێڕ و کانزاکان',
      'wallstreet_stocks': '📈 پشکەکانی واڵ ستریت',
      'global_indices': '🌐 پێوەرە جیهانییەکان',
      'price_cross_above': 'تێپەڕین بۆ سەرەوە (▲)',
      'price_cross_below': 'دابەزین بۆ خوارەوە (▼)',
      'price_cross_direction': 'ئاراستەی تێپەڕین:',
      'above_target': '▲ سەرووی مەبەست',
      'below_target': '▼ خوارووی مەبەست',
      'price_fluctuation': 'گۆڕانی نرخ:',
      'price_surge': 'بەرزبوونەوەی نرخ:',
      'price_drop': 'دابەزینی نرخ:',
      'target_price_summary': 'نرخی مەبەست:',
      'price_delta_summary': 'گۆڕانی دۆلاری:',
      'volume_surge_summary': 'بەرزبوونەوەی قەبارە:',
      'interval_prefix': '⏱️ پشکنینی نرخ هەر ',
      'interval_suffix': ' جارێک لە پاشبنەما ئەنجام دەدرێت.',
      'offline_error': 'هێڵی ئینتەرنێت نییە. دواین نرخ پارێزراوە.',
      'offline_badge': 'ئۆفلاین',
      'edit_alert_title': 'دەستکاری ئاگاداری',
      'save_changes_cta': 'پاشەکەوتکردنی گۆڕانکارییەکان',
      'sound_and_vibrate_section': '٣. ڕێکخستنی دەنگ، لەرزین و تێبینی:',
      'sound_and_vibrate_sub': 'تایبەتکردنی ئاگاداری بۆ ئەم مەرجە',
      'custom_note_title': 'دەقی تێبینی ئاگاداری',
      'custom_note_hint': 'نموونە: ئامانجی ۱ پێکرا - قازانج وەرگرە!',
      'alarm_sound_title': 'دەنگی ئەم ئاگادارییە',
      'change_sound_btn': 'گۆڕینی دەنگ',
      'play_sound_label': 'لێدانی دەنگ',
      'vibrate_phone_label': 'لەرزینی مۆبایل',
      'select_alarm_sound': 'هەڵبژاردنی دەنگی ئاگاداری',
      'confirm_sound_btn': 'پەسەندکردنی دەنگ',
      'live_market_price': 'نرخی ئێستای بازاڕ:',
      'fetching_live_price': 'وەرگرتنی نرخ...',
      'live_price_unavailable': 'نرخ بەردەست نییە',
      'manual_monitoring': 'چاودێری دەستی',
      'symbol_not_found': 'هیچ هێمایەک نەدۆزرایەوە',
      'triggers_count': 'لێدانەکان:',
      'last_trigger': 'دواین:',
      'trigger_price_label': 'نرخی لێدان:',
      'duplicate_action': 'دووبارەکردنەوە',
      'edit_action': 'دەستکاری',
      'delete_action': 'سڕینەوە',
      'cooldown_active': 'کاتی پشوو (Cooldown)',
      'alarm_volume_label': 'بەرزی دەنگی ئاگاداری',
      'selected_sound_label': 'دەنگی هەڵبژێردراو',
      'sound_alarm_siren_title': '🚨 هاواری کتوپڕ (Siren)',
      'sound_radar_pulse_title': '📡 ڕاداری ئامانج (Radar)',
      'sound_cyber_chime_title': '⚡ زەنگی سایبەر (Cyber)',
      'sound_crystal_ping_title': '💎 پینگی کریستاڵ (Crystal)',
      'sound_bullish_rise_title': '📈 بەرزبوونەوەی نرخ (Ascend)',
      'sound_coin_drop_title': '🪙 دەنگی دراو (Coin)',
      'sound_alert_horn_title': '🎺 هوڕڕای ئاگاداری (Horn)',
      'sound_classic_beep_title': '📟 بیپی کلاسیک (Beep)',
      'cat_all_exchanges': 'هەموو بۆرسەکان',
      'cat_tier1': 'پلەی یەکەم (Tier-1)',
      'cat_middle_east': 'ڕۆژهەڵاتی ناوەڕاست',
      'cat_asia': 'ئاسیا و ڕۆژهەڵاتی دوور',
      'cat_europe': 'ئەوروپا',
      'cat_americas': 'ئەمریکا و ئەوانی تر',
      'cat_aggregator': 'سەرچاوە و پێوەرەکان',
      'retry_btn': 'دووبارە هەوڵبدەرەوە',
      'date_today': 'ئەمڕۆ',
      'date_yesterday': 'دوێنێ',
      'rule_copied': 'کۆدی JSON لە کلیپبۆرد کۆپیکرا',
      'format_error_json': 'هەڵەی فۆرمات لە فایلی JSON.',
      'rearm_now_btn': 'چالاککردنەوەی خێرا',
      'rearm_dialog_title': 'چالاککردنەوەی ئاگاداری؟',
      'rearm_dialog_body': 'پشووی ئاگادارییەکە کۆتایی پێدێت و چاودێری دەستپێدەکاتەوە.',
      'alert_rule_duplicated': 'ئاگاداری بە سەرکەوتوویی دووبارەکرایەوە',
      'export_rule_action': 'دەرهێنانی یاسا (JSON)',
      'popular_cryptos': 'دراوە بەناوبانگەکان:',
    },

    // 4. ARABIC (العربية - RTL)
    'ar': {
      'my_alerts': 'تنبيهاتي',
      'history': 'السجل',
      'settings': 'الإعدادات',
      'smart_alerts_desc': 'مراقبة ذكية للأسعار حسب جدول زمني مخصص',
      'new_alert': 'إضافة تنبيه جديد',
      'last_checked_price': 'آخر سعر تم فحصه:',
      'check_now': 'فحص فوري',
      'baseline': 'الأساس',
      'rearm': 'إعادة التفعيل',
      'theme_and_colors': 'المظهر والألوان',
      'theme_dark_green': 'الزمردي الداكن (الافتراضي)',
      'theme_light_green': 'الزمردي الفاتح',
      'theme_dark_orange': 'البرتقالي الداكن',
      'theme_light_orange': 'البرتقالي الفاتح',
      'theme_dark_purple_blue': 'أرجواني أزرق داكن',
      'theme_light_purple_blue': 'أرجواني أزرق فاتح',
      'tts_voice_title': 'النطق الصوتي الذكي (Text-to-Speech)',
      'tts_voice_desc': 'ينطق اسم العملة والسعر بصوت طبيعي عند انطلاق التنبيه',
      'tts_test_button': '🗣️ اختبار النطق الصوتي',
      'home_widget_title': 'أداة الشاشة الرئيسية المباشرة',
      'home_widget_desc': 'مراقبة التنبيهات المباشرة والقرب من الهدف على الشاشة الرئيسية',
      'select_language': 'لغة التطبيق',
      'sound_and_vibrate': 'الصوت والاهتزاز',
      'sound_alert': 'صوت المنبه والإنذار',
      'vibrate_alert': 'الاهتزاز عند التنبيه',
      'test_sound_button': '🔔 اختبار صوت التنبيه والإشعار',
      'backup_and_restore': 'النسخ الاحتياطي والاستعادة',
      'export_backup': 'تصدير التنبيهات (JSON)',
      'restore_backup': 'استعادة التنبيهات (JSON)',
      'clear_history': 'مسح سجل الإشعارات',
      'battery_settings': 'تحسين البطارية (Android)',
      'battery_active': 'مستثنى من تحسين البطارية',
      'battery_request': 'طلب الاستثناء',
      'test_alert_title': 'إشعار اختبار المنبه',
      'test_alert_body': 'تم إطلاق صوت التنبيه والإشعار بنجاح على جهازك!',
      'backup_copied': '✅ تم نسخ النسخة الاحتياطية إلى الحافظة بنجاح.',
      'restore_success': 'تمت استعادة التنبيهات بنجاح.',
      'exchange': 'المنصة',
      'pair': 'زوج التداول',
      'create_alert_title': 'إنشاء تنبيه ذكي',
      'frequency': 'فترة الفحص',
      'seconds': 'ثانية',
      'minutes': 'دقيقة',
      'hours': 'ساعة',
      'empty_alerts_title': 'لم يتم ضبط أي تنبيهات بعد',
      'empty_alerts_desc': 'يمكنك ضبط تنبيهات لتغير النسبة المئوية أو السعر المستهدف للعملات المشفرة وسندات الخزانة والأسهم العالمية.',
      'create_first_alert': 'إنشاء أول تنبيه ذكي',
      'choose_market_step': 'الخطوة الأولى: اختيار نوع السوق',
      'choose_market_title': 'ما السوق الذي ترغب في متابعته؟',
      'choose_market_desc': 'حدد نوع السوق والأصل المطلوب لمراقبة الأسعار بدقة.',
      'crypto_market_title': '⚡ سوق العملات المشفرة (Crypto)',
      'crypto_market_badge': 'أكثر من ٤٠ منصة معتمدة',
      'crypto_market_desc': 'أكثر من ٤٠ منصة دولية ومحلية مع فلاتر التصنيف وجلب أزواج التداول وزر التحديث.',
      'crypto_market_cta': 'الدخول إلى منصات العملات المشفرة ←',
      'macro_market_title': '🏛️ الأسهم الأمريكية وسندات الخزانة والفوركس',
      'macro_market_badge': 'وول ستريت والاقتصاد الكلي',
      'macro_market_desc': 'سندات الخزانة الأمريكية (US10Y) وأزواج الفوركس وأسهم ناسداك والذهب والمؤشرات.',
      'macro_market_cta': 'الدخول إلى الأسواق العالمية ←',
      'search_exchange_hint': 'البحث عن منصة (Binance, Nobitex, Wallex, KuCoin)...',
      'search_crypto_hint': 'البحث عن عملة (BTC, ETH, SOL, POL, DOGE)...',
      'search_macro_hint': 'البحث عن رمز (US10Y, EUR/USD, NVDA, الذهب)...',
      'refresh_list': 'تحديث القائمة',
      'select_cta': 'اختيار ←',
      'selected_asset': 'الأصل المحدد:',
      'auto_check_schedule': '١. جدول الفحص التلقائي:',
      'unit_count': 'القيمة',
      'time_unit': 'وحدة الوقت',
      'condition_type': '٢. نوع شرط التنبيه:',
      'percent_change': 'نسبة التغير (%)',
      'price_target': 'السعر المستهدف (\$)',
      'price_direction': 'اتجاه حركة السعر:',
      'both_ways': '± كلا الاتجاهين',
      'above_only': '▲ ارتفاع فقط',
      'below_only': '▼ انخفاض فقط',
      'target_price_label': 'السعر المستهدف (بالدولار)',
      'percent_label': 'النسبة المئوية المطلوبة (%)',
      'save_alert_cta': 'حفظ وبدء المراقبة',
      'just_now': 'الآن',
      'seconds_ago': 'ثوانٍ مضت',
      'minutes_ago': 'دقائق مضت',
      'hours_ago': 'ساعات مضت',
      'days_ago': 'أيام مضت',
      'every': 'كل',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'restore_dialog_hint': 'الصق نص النسخة الاحتياطية JSON في المربع أدناه:',
      'restore_dialog_btn': 'تأكيد واستعادة',
      'clear_history_confirm': 'هل أنت متأكد من رغبتك في مسح كافة سجلات الإشعارات؟',
      'clear_history_btn': 'مسح الكل',
      'clear_history_success': 'تم مسح كافة سجلات الإشعارات بنجاح.',
      'battery_exempt_active': 'نشط (تعمل التنبيهات في موعدها بدقة)',
      'battery_exempt_inactive': 'غير نشط (قد يوقف النظام التنبيهات في الخلفية)',
      'battery_exempt_title': 'استثناء تحسين البطارية',
      'battery_exempt_success': 'تم منح استثناء البطارية بنجاح.',
      'export_backup_desc': 'تصدير جميع التنبيهات النشطة إلى ملف JSON',
      'restore_backup_desc': 'استيراد واستعادة التنبيهات من ملف أو نص JSON',
      'clear_history_desc': 'حذف جميع السجلات والتنبيهات السابقة',
      'filter_all': 'الكل',
      'filter_triggered': 'المنفذة',
      'filter_suppressed': 'المقيدة',
      'no_history_title': 'لا يوجد سجل بعد',
      'no_history_desc': 'عند تحقق شروط التنبيه، سيتم تسجيل الأحداث هنا.',
      'check_price_done': 'تم فحص السعر: ',
      'alert_deleted_msg': 'تم حذف التنبيه: ',
      'undo_action': 'تراجع',
      'target_price_required': 'يرجى إدخال السعر المستهدف',
      'all_symbols': 'كافة الرموز',
      'us_bonds': '🏛️ سندات الخزانة الأمريكية',
      'forex_pairs': '💱 أزواج الفوركس',
      'gold_metals': '🥇 الذهب والمعادن',
      'wallstreet_stocks': '📈 أسهم وول ستريت',
      'global_indices': '🌐 المؤشرات العالمية',
      'price_cross_above': 'تجاوز للأعلى (▲)',
      'price_cross_below': 'هبوط للأسفل (▼)',
      'price_cross_direction': 'اتجاه التجاوز:',
      'above_target': '▲ أعلى من المستهدف',
      'below_target': '▼ أدنى من المستهدف',
      'price_fluctuation': 'تغير السعر:',
      'price_surge': 'ارتفاع السعر:',
      'price_drop': 'انخفاض السعر:',
      'target_price_summary': 'السعر المستهدف:',
      'price_delta_summary': 'فارق السعر:',
      'volume_surge_summary': 'قفزة في حجم التداول:',
      'interval_prefix': '⏱️ يتم فحص السعر تلقائياً كل ',
      'interval_suffix': ' في الخلفية.',
      'offline_error': 'لا يوجد اتصال بالإنترنت. تم الاحتفاظ بآخر سعر.',
      'offline_badge': 'أوفلاين',
      'edit_alert_title': 'تعديل التنبيه',
      'save_changes_cta': 'حفظ التعديلات',
      'sound_and_vibrate_section': '٣. إعدادات الصوت والاهتزاز والرسالة:',
      'sound_and_vibrate_sub': 'تخصيص نغمة ورسالة التنبيه لهذا الشرط',
      'custom_note_title': 'رسالة / ملاحظة مخصصة عند التنبيه',
      'custom_note_hint': 'مثال: تم الوصول للهدف الأول - احجز 50% من الأرباح!',
      'alarm_sound_title': 'نغمة هذا التنبيه',
      'change_sound_btn': 'تغيير النغمة',
      'play_sound_label': 'تشغيل الصوت',
      'vibrate_phone_label': 'اهتزاز الهاتف',
      'select_alarm_sound': 'اختيار نغمة التنبيه',
      'confirm_sound_btn': 'تأكيد وحفظ النغمة',
      'live_market_price': 'السعر الفوري للسوق:',
      'fetching_live_price': 'جاري جلب السعر الفوري...',
      'live_price_unavailable': 'السعر الفوري غير متاح',
      'manual_monitoring': 'مراقبة يدوية',
      'symbol_not_found': 'لم يتم العثور على أي رمز',
      'triggers_count': 'مرات التشغيل:',
      'last_trigger': 'آخر تنفيذ:',
      'trigger_price_label': 'سعر التفعيل:',
      'duplicate_action': 'تكرار التنبيه',
      'edit_action': 'تعديل',
      'delete_action': 'حذف',
      'cooldown_active': 'فترة استراحة (Cooldown)',
      'alarm_volume_label': 'مستوى صوت المنبه',
      'selected_sound_label': 'نغمة المنبه المختارة',
      'sound_alarm_siren_title': '🚨 صفارة إنذار طارئة (Siren)',
      'sound_radar_pulse_title': '📡 نبضات رادار الهدف (Radar)',
      'sound_cyber_chime_title': '⚡ رنين سيبراني رقمي (Cyber)',
      'sound_crystal_ping_title': '💎 رنين كريستالي نقي (Crystal)',
      'sound_bullish_rise_title': '📈 صعود سعري حاد (Ascend)',
      'sound_coin_drop_title': '🪙 صوت سقوط العملات (Coin)',
      'sound_alert_horn_title': '🎺 بوق تنبيه السوق (Horn)',
      'sound_classic_beep_title': '📟 رنين منصة كلاسيكي (Beep)',
      'cat_all_exchanges': 'جميع منصات التداول',
      'cat_tier1': 'العالمية الأولى (Tier-1)',
      'cat_middle_east': 'الشرق الأوسط وإيران',
      'cat_asia': 'آسيا والشرق الأقصى',
      'cat_europe': 'أوروبا',
      'cat_americas': 'الأمريكتان وأخرى',
      'cat_aggregator': 'المجمعات والمؤشرات',
      'retry_btn': 'إعادة المحاولة',
      'date_today': 'اليوم',
      'date_yesterday': 'أمس',
      'rule_copied': 'تم نسخ كود التنبيه إلى الحافظة',
      'format_error_json': 'خطأ في تنسيق ملف النسخ الاحتياطي JSON.',
      'rearm_now_btn': 'إعادة التفعيل الفوري',
      'rearm_dialog_title': 'إعادة تفعيل التنبيه الآن؟',
      'rearm_dialog_body': 'سيؤدي هذا إلى إنهاء فترة الاستراحة فوراً واستئناف التنبيهات.',
      'alert_rule_duplicated': 'تم تكرار التنبيه بنجاح',
      'export_rule_action': 'تصدير التنبيه (JSON)',
      'popular_cryptos': 'العملات المشفرة الشائعة:',
    },

    // 5. TURKISH (Türkçe - LTR)
    'tr': {
      'my_alerts': 'Alarmlarım',
      'history': 'Geçmiş',
      'settings': 'Ayarlar',
      'smart_alerts_desc': 'Özel zamanlamaya göre akıllı fiyat takibi',
      'new_alert': 'Yeni Alarm Ekle',
      'last_checked_price': 'Son Kontrol Edilen Fiyat:',
      'check_now': 'Şimdi Kontrol Et',
      'baseline': 'Baz',
      'rearm': 'Yeniden Kur',
      'theme_and_colors': 'Tema ve Renkler',
      'theme_dark_green': 'Koyu Zümrüt (Varsayılan)',
      'theme_light_green': 'Açık Zümrüt',
      'theme_dark_orange': 'Koyu Turuncu',
      'theme_light_orange': 'Açık Turuncu',
      'theme_dark_purple_blue': 'Koyu Mor Mavi',
      'theme_light_purple_blue': 'Açık Mor Mavi',
      'tts_voice_title': 'Akıllı Sesli Okuma (Text-to-Speech)',
      'tts_voice_desc': 'Alarm tetiklendiğinde para birimi ve fiyatı sesli olarak okur',
      'tts_test_button': '🗣️ Ses Testi',
      'home_widget_title': 'Canlı Ana Ekran Widgetı',
      'home_widget_desc': 'Ana ekranda canlı alarm takibi ve hedefe yakınlık durumu',
      'select_language': 'Uygulama Dili',
      'sound_and_vibrate': 'Ses ve Titreşim',
      'sound_alert': 'Alarm Sesi',
      'vibrate_alert': 'Alarmda Titreşim',
      'test_sound_button': '🔔 Alarm ve Bildirimi Test Et',
      'backup_and_restore': 'Yedekleme ve Geri Yükleme',
      'export_backup': 'Alarmları Dışa Aktar (JSON)',
      'restore_backup': 'Alarmları Geri Yükle (JSON)',
      'clear_history': 'Bildirim Geçmişini Temizle',
      'battery_settings': 'Pil Optimizasyonu (Android)',
      'battery_active': 'Pil kısıtlamasından muaf (Güvenilir)',
      'battery_request': 'Muafiyet İste',
      'test_alert_title': 'Alarmer Test Bildirimi',
      'test_alert_body': 'Ses ve bildirim cihazınızda başarıyla tetiklendi!',
      'backup_copied': '✅ Yedek panoya başarıyla kopyalandı.',
      'restore_success': 'Alarmlar başarıyla geri yüklendi.',
      'exchange': 'Borsa',
      'pair': 'İşlem Çifti',
      'create_alert_title': 'Akıllı Alarm Oluştur',
      'frequency': 'Kontrol Sıklığı',
      'seconds': 'Saniye',
      'minutes': 'Dakika',
      'hours': 'Saat',
      'empty_alerts_title': 'Henüz Alarm Ayarlanmadı',
      'empty_alerts_desc': 'Kripto, ABD tahvilleri veya küresel hisseler için alarm kurabilirsiniz.',
      'create_first_alert': 'İlk Akıllı Alarmı Oluştur',
      'choose_market_step': '1. Adım: Piyasa Türünü Seçin',
      'choose_market_title': 'Hangi piyasayı takip etmek istersiniz?',
      'choose_market_desc': 'Fiyatları doğru izlemek için piyasa ve varlığı seçin.',
      'crypto_market_title': '⚡ Kripto Para Piyasası',
      'crypto_market_badge': '40+ Doğrulanmış Borsa',
      'crypto_market_desc': '40+ uluslararası borsa, filtreler ve otomatik çift bulma.',
      'crypto_market_cta': 'Kripto Borsalarına Gir →',
      'macro_market_title': '🏛️ ABD Hisseleri, Tahviller ve Forex',
      'macro_market_badge': 'Wall Street ve Makro Ekonomi',
      'macro_market_desc': 'ABD 10 Yıllık Tahvilleri (US10Y), Forex, Nasdaq/NYSE hisseleri ve Altın.',
      'macro_market_cta': 'Küresel Piyasalara Gir →',
      'search_exchange_hint': 'Borsa ara (Binance, KuCoin, Nobitex)...',
      'search_crypto_hint': 'Kripto ara (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'Sembol ara (US10Y, EUR/USD, NVDA, Altın)...',
      'refresh_list': 'Listeyi Yenile',
      'select_cta': 'Seç →',
      'selected_asset': 'Seçilen Varlık:',
      'auto_check_schedule': '1. Otomatik Kontrol Zamanı:',
      'unit_count': 'Aralık Değeri',
      'time_unit': 'Zaman Birimi',
      'condition_type': '2. Alarm Koşulu Türü:',
      'percent_change': 'Yüzde Değişimi (%)',
      'price_target': 'Hedef Fiyat (\$)',
      'price_direction': 'Fiyat Yönü:',
      'both_ways': '± Her İki Yön',
      'above_only': '▲ Yalnızca Yükseliş',
      'below_only': '▼ Yalnızca Düşüş',
      'target_price_label': 'Hedef Fiyat (\$)',
      'percent_label': 'Hedef Yüzde (%)',
      'save_alert_cta': 'Kaydet ve Takibi Başlat',
      'just_now': 'Az önce',
      'seconds_ago': 'sn önce',
      'minutes_ago': 'dk önce',
      'hours_ago': 'sa önce',
      'days_ago': 'gün önce',
      'every': 'Her',
      'cancel': 'İptal',
      'confirm': 'Onayla',
      'restore_dialog_hint': 'JSON yedek metnini aşağıdaki kutuya yapıştırın:',
      'restore_dialog_btn': 'Onayla ve Geri Yükle',
      'clear_history_confirm': 'Tüm bildirim geçmişini silmek istediğinizden emin misiniz?',
      'clear_history_btn': 'Tümünü Temizle',
      'clear_history_success': 'Bildirim geçmişi temizlendi.',
      'battery_exempt_active': 'Aktif (Alarmlar tam zamanında çalışır)',
      'battery_exempt_inactive': 'Pasif (Arka plan görevleri durdurulabilir)',
      'battery_exempt_title': 'Pil Optimizasyonu Muafiyeti',
      'battery_exempt_success': 'Pil muafiyeti başarıyla tanımlandı.',
      'export_backup_desc': 'Aktif alarmları JSON dosyası olarak dışa aktar',
      'restore_backup_desc': 'JSON metninden alarmları içeri aktar',
      'clear_history_desc': 'Kayıtlı tüm bildirim geçmişini sil',
      'filter_all': 'Tümü',
      'filter_triggered': 'Tetiklenenler',
      'filter_suppressed': 'Kısıtlananlar',
      'no_history_title': 'Henüz Geçmiş Yok',
      'no_history_desc': 'Fiyat koşulları karşılandığında olaylar burada listelenir.',
      'check_price_done': 'Fiyat kontrolü yapıldı: ',
      'alert_deleted_msg': 'Alarm silindi: ',
      'undo_action': 'Geri Al',
      'target_price_required': 'Lütfen bir hedef fiyat girin',
      'all_symbols': 'Tüm Varlıklar',
      'us_bonds': '🏛️ ABD Hazine Tahvilleri',
      'forex_pairs': '💱 Forex Çiftleri',
      'gold_metals': '🥇 Altın ve Metaller',
      'wallstreet_stocks': '📈 Wall Street Hisseleri',
      'global_indices': '🌐 Küresel Endeksler',
      'price_cross_above': 'Üzerine çıkış (▲)',
      'price_cross_below': 'Altına düşüş (▼)',
      'price_cross_direction': 'Kesişim Yönü:',
      'above_target': '▲ Hedefin Üzerinde',
      'below_target': '▼ Hedefin Altında',
      'price_fluctuation': 'Fiyat değişimi:',
      'price_surge': 'Fiyat artışı:',
      'price_drop': 'Fiyat düşüşü:',
      'target_price_summary': 'Hedef fiyat:',
      'price_delta_summary': 'Dolar farkı:',
      'volume_surge_summary': 'Hacim artışı:',
      'interval_prefix': '⏱️ Fiyat kontrolü her ',
      'interval_suffix': ' bir kez arka planda çalışır.',
      'offline_error': 'İnternet bağlantısı yok. Son gerçek fiyat korunuyor.',
      'offline_badge': 'Çevrimdışı',
      'edit_alert_title': 'Alarmı Düzenle',
      'save_changes_cta': 'Değişiklikleri Kaydet',
      'sound_and_vibrate_section': '3. Ses, Titreşim ve Özel Not Ayarları:',
      'sound_and_vibrate_sub': 'Bu koşul için özel bildirim ayarlarını yapılandırın',
      'custom_note_title': 'Özel Alarm Mesajı / Not',
      'custom_note_hint': 'Örn: Hedef 1 ulaşıldı - %50 kâr al!',
      'alarm_sound_title': 'Bu Alarmın Zil Sesi',
      'change_sound_btn': 'Sesi Değiştir',
      'play_sound_label': 'Sesi Çal',
      'vibrate_phone_label': 'Telefonu Titret',
      'select_alarm_sound': 'Alarm Sesi Seç',
      'confirm_sound_btn': 'Sesi Onayla ve Kaydet',
      'live_market_price': 'Canlı Piyasa Fiyatı:',
      'fetching_live_price': 'Canlı fiyat alınıyor...',
      'live_price_unavailable': 'Canlı fiyat mevcut değil',
      'manual_monitoring': 'Manuel İzleme',
      'symbol_not_found': 'Eşleşen sembol bulunamadı',
      'triggers_count': 'Tetiklenme:',
      'last_trigger': 'Son:',
      'trigger_price_label': 'Tetiklenme Fiyatı:',
      'duplicate_action': 'Çoğalt',
      'edit_action': 'Düzenle',
      'delete_action': 'Sil',
      'cooldown_active': 'Bekleme Süresi (Cooldown)',
      'alarm_volume_label': 'Alarm Ses Seviyesi',
      'selected_sound_label': 'Seçilen Alarm Sesi',
      'sound_alarm_siren_title': '🚨 Acil Durum Sireni (Siren)',
      'sound_radar_pulse_title': '📡 Radar Hedef Palsı (Radar)',
      'sound_cyber_chime_title': '⚡ Siber İşlem Sesi (Cyber)',
      'sound_crystal_ping_title': '💎 Kristal Netliğinde Ping (Crystal)',
      'sound_bullish_rise_title': '📈 Yükseliş Artışı (Ascend)',
      'sound_coin_drop_title': '🪙 Dijital Para Sesi (Coin)',
      'sound_alert_horn_title': '🎺 Piyasa Uyarı Kornası (Horn)',
      'sound_classic_beep_title': '📟 Klasik Borsa Bipi (Beep)',
      'cat_all_exchanges': 'Tüm Kripto Borsaları',
      'cat_tier1': 'Birinci Seviye (Tier-1)',
      'cat_middle_east': 'Orta Doğu ve İran',
      'cat_asia': 'Asya ve Uzak Doğu',
      'cat_europe': 'Avrupa',
      'cat_americas': 'Amerika ve Diğerleri',
      'cat_aggregator': 'Toplayıcılar ve Endeksler',
      'retry_btn': 'Tekrar Dene',
      'date_today': 'Bugün',
      'date_yesterday': 'Dün',
      'rule_copied': 'Kural JSON panoya kopyalandı',
      'format_error_json': 'JSON yedek dosyasında biçim hatası.',
      'rearm_now_btn': 'Şimdi Yeniden Kur',
      'rearm_dialog_title': 'Alarmı Şimdi Yeniden Kur?',
      'rearm_dialog_body': 'Bekleme süresi derhal sonlandırılacak ve gerçek zamanlı takip devam edecektir.',
      'alert_rule_duplicated': 'Alarm kuralı başarıyla çoğaltıldı',
      'export_rule_action': 'Kuralı Dışa Aktar (JSON)',
      'popular_cryptos': 'Popüler Kripto Paralar:',
    },

    // 6. GERMAN (Deutsch - LTR)
    'de': {
      'my_alerts': 'Meine Alarme',
      'history': 'Verlauf',
      'settings': 'Einstellungen',
      'smart_alerts_desc': 'Intelligente Überwachung nach individuellem Zeitplan',
      'new_alert': 'Neuer Alarm',
      'last_checked_price': 'Zuletzt geprüfter Preis:',
      'check_now': 'Jetzt prüfen',
      'baseline': 'Basis',
      'rearm': 'Erneut scharfstellen',
      'theme_and_colors': 'Design & Farbpalette',
      'theme_dark_green': 'Dunkel-Smaragd (Standard)',
      'theme_light_green': 'Hell-Smaragd',
      'theme_dark_orange': 'Dunkel-Orange',
      'theme_light_orange': 'Hell-Orange',
      'theme_dark_purple_blue': 'Dunkel Lila-Blau',
      'theme_light_purple_blue': 'Hell Lila-Blau',
      'tts_voice_title': 'Intelligente Sprachansage (TTS)',
      'tts_voice_desc': 'Liest Währung und Kurs bei Alarmauslösung mit natürlicher Stimme vor',
      'tts_test_button': '🗣️ Sprachausgabe testen',
      'home_widget_title': 'Live Startbildschirm-Widget',
      'home_widget_desc': 'Echtzeit-Alarmüberwachung und Zielabstand auf dem Startbildschirm',
      'select_language': 'Sprache',
      'sound_and_vibrate': 'Ton & Vibration',
      'sound_alert': 'Alarmton',
      'vibrate_alert': 'Vibrationsalarm',
      'test_sound_button': '🔔 Alarm & Benachrichtigung testen',
      'backup_and_restore': 'Sicherung & Wiederherstellung',
      'export_backup': 'Alarme exportieren (JSON)',
      'restore_backup': 'Alarme wiederherstellen (JSON)',
      'clear_history': 'Benachrichtigungsverlauf löschen',
      'battery_settings': 'Akku-Optimierung (Android)',
      'battery_active': 'Von Akku-Optimierung ausgenommen',
      'battery_request': 'Ausnahme anfordern',
      'test_alert_title': 'Alarmer Testbenachrichtigung',
      'test_alert_body': 'Ton und Benachrichtigung wurden erfolgreich auf Ihrem Gerät ausgelöst!',
      'backup_copied': '✅ Sicherung erfolgreich in die Zwischenablage kopiert.',
      'restore_success': 'Alarme erfolgreich wiederhergestellt.',
      'exchange': 'Börse',
      'pair': 'Handelspaar',
      'create_alert_title': 'Smart-Alarm erstellen',
      'frequency': 'Intervall',
      'seconds': 'Sek',
      'minutes': 'Min',
      'hours': 'Std',
      'empty_alerts_title': 'Noch keine Alarme konfiguriert',
      'empty_alerts_desc': 'Erstellen Sie prozentuale oder Zielpreis-Alarme für Krypto, US-Anleihen oder Aktien.',
      'create_first_alert': 'Ersten Smart-Alarm erstellen',
      'choose_market_step': 'Schritt 1: Markt wählen',
      'choose_market_title': 'Welchen Markt möchten Sie überwachen?',
      'choose_market_desc': 'Wählen Sie den Markt und das gewünschte Asset aus.',
      'crypto_market_title': '⚡ Krypto-Markt (Kryptowährungen)',
      'crypto_market_badge': 'Über 40 verifizierte Börsen',
      'crypto_market_desc': 'Über 40 Top-Börsen mit Kategoriefiltern und Paar-Erkennung.',
      'crypto_market_cta': 'Zu den Krypto-Börsen →',
      'macro_market_title': '🏛️ US-Aktien, Anleihen & Forex',
      'macro_market_badge': 'Wall Street & Makroökonomie',
      'macro_market_desc': 'US 10-Jahres-Renditen (US10Y), Forex, Nasdaq/NYSE Aktien & Gold.',
      'macro_market_cta': 'Zu den globalen Märkten →',
      'search_exchange_hint': 'Börse suchen (Binance, Nobitex, Wallex, KuCoin)...',
      'search_crypto_hint': 'Krypto suchen (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'Symbol suchen (US10Y, EUR/USD, NVDA, Gold)...',
      'refresh_list': 'Paare aktualisieren',
      'select_cta': 'Auswählen →',
      'selected_asset': 'Ausgewähltes Asset:',
      'auto_check_schedule': '1. Automatischer Prüfzeitplan:',
      'unit_count': 'Intervallwert',
      'time_unit': 'Zeiteinheit',
      'condition_type': '2. Alarmbedingung:',
      'percent_change': 'Prozentuale Änderung (%)',
      'price_target': 'Zielpreis (\$)',
      'price_direction': 'Kursrichtung:',
      'both_ways': '± Beide Richtungen',
      'above_only': '▲ Nur Anstieg',
      'below_only': '▼ Nur Rückgang',
      'target_price_label': 'Zielpreis (\$)',
      'percent_label': 'Prozentsatz (%)',
      'save_alert_cta': 'Speichern und Überwachung starten',
      'just_now': 'Gerade eben',
      'seconds_ago': 'vor s',
      'minutes_ago': 'vor m',
      'hours_ago': 'vor h',
      'days_ago': 'vor d',
      'every': 'Alle',
      'cancel': 'Abbrechen',
      'confirm': 'Bestätigen',
      'restore_dialog_hint': 'Fügen Sie den JSON-Sicherungstext in das Feld ein:',
      'restore_dialog_btn': 'Bestätigen & Wiederherstellen',
      'clear_history_confirm': 'Möchten Sie wirklich den gesamten Benachrichtigungsverlauf löschen?',
      'clear_history_btn': 'Alles löschen',
      'clear_history_success': 'Der Benachrichtigungsverlauf wurde gelöscht.',
      'battery_exempt_active': 'Aktiv (Alarme laufen pünktlich im Hintergrund)',
      'battery_exempt_inactive': 'Inaktiv (Hintergrundprüfungen können pausiert werden)',
      'battery_exempt_title': 'Akku-Optimierungs-Ausnahme',
      'battery_exempt_success': 'Ausnahme erfolgreich erteilt.',
      'export_backup_desc': 'Alle aktiven Alarme als JSON exportieren',
      'restore_backup_desc': 'Alarme aus JSON-Text importieren',
      'clear_history_desc': 'Alle gespeicherten Protokolle löschen',
      'filter_all': 'Alle',
      'filter_triggered': 'Ausgelöst',
      'filter_suppressed': 'Unterdrückt',
      'no_history_title': 'Noch kein Verlauf vorhanden',
      'no_history_desc': 'Wenn Alarmbedingungen erfüllt sind, erscheinen die Ereignisse hier.',
      'check_price_done': 'Preisprüfung abgeschlossen: ',
      'alert_deleted_msg': 'Alarm gelöscht: ',
      'undo_action': 'Rückgängig',
      'target_price_required': 'Bitte geben Sie einen Zielpreis ein',
      'all_symbols': 'Alle Assets',
      'us_bonds': '🏛️ US-Staatsanleihen',
      'forex_pairs': '💱 Forex-Paare',
      'gold_metals': '🥇 Gold & Metalle',
      'wallstreet_stocks': '📈 Wall-Street-Aktien',
      'global_indices': '🌐 Globale Indizes',
      'price_cross_above': 'Übersteigt (▲)',
      'price_cross_below': 'Fällt unter (▼)',
      'price_cross_direction': 'Kreuzungsrichtung:',
      'above_target': '▲ Über dem Ziel',
      'below_target': '▼ Unter dem Ziel',
      'price_fluctuation': 'Preisänderung:',
      'price_surge': 'Preisanstieg:',
      'price_drop': 'Preisrückgang:',
      'target_price_summary': 'Zielpreis:',
      'price_delta_summary': 'Preis-Delta:',
      'volume_surge_summary': 'Volumenanstieg:',
      'interval_prefix': '⏱️ Die Preisprüfung läuft alle ',
      'interval_suffix': ' im Hintergrund.',
      'offline_error': 'Keine Internetverbindung. Letzter echter Preis wird beibehalten.',
      'offline_badge': 'Offline',
      'edit_alert_title': 'Alarm bearbeiten',
      'save_changes_cta': 'Änderungen speichern',
      'sound_and_vibrate_section': '3. Ton-, Vibrations- und Notizeinstellungen:',
      'sound_and_vibrate_sub': 'Benachrichtigung für diese Bedingung anpassen',
      'custom_note_title': 'Eigene Nachricht / Notiz',
      'custom_note_hint': 'z. B. Ziel 1 erreicht - 50 % Gewinn mitnehmen!',
      'alarm_sound_title': 'Alarmton für diesen Alarm',
      'change_sound_btn': 'Ton ändern',
      'play_sound_label': 'Ton abspielen',
      'vibrate_phone_label': 'Vibration',
      'select_alarm_sound': 'Alarmton wählen',
      'confirm_sound_btn': 'Ton bestätigen & speichern',
      'live_market_price': 'Live-Marktpreis:',
      'fetching_live_price': 'Live-Preis wird abgerufen...',
      'live_price_unavailable': 'Live-Preis nicht verfügbar',
      'manual_monitoring': 'Manuelle Überwachung',
      'symbol_not_found': 'Keine passenden Symbole gefunden',
      'triggers_count': 'Auslösungen:',
      'last_trigger': 'Zuletzt:',
      'trigger_price_label': 'Auslösepreis:',
      'duplicate_action': 'Duplizieren',
      'edit_action': 'Bearbeiten',
      'delete_action': 'Löschen',
      'cooldown_active': 'Abklingzeit (Cooldown)',
      'alarm_volume_label': 'Alarmlautstärke',
      'selected_sound_label': 'Ausgewählter Alarmton',
      'sound_alarm_siren_title': '🚨 Notfallsirene (Siren)',
      'sound_radar_pulse_title': '📡 Radar-Zielpuls (Radar)',
      'sound_cyber_chime_title': '⚡ Cyber-Handelsklang (Cyber)',
      'sound_crystal_ping_title': '💎 Kristallklares Ping (Crystal)',
      'sound_bullish_rise_title': '📈 Bullischer Preisanstieg (Ascend)',
      'sound_coin_drop_title': '🪙 Digitaler Münzfall (Coin)',
      'sound_alert_horn_title': '🎺 Marktwarnhorn (Horn)',
      'sound_classic_beep_title': '📟 Klassischer Börsen-Beep (Beep)',
      'cat_all_exchanges': 'Alle Krypto-Börsen',
      'cat_tier1': 'Tier-1 Global',
      'cat_middle_east': 'Naher Osten & Iran',
      'cat_asia': 'Asien & Fernost',
      'cat_europe': 'Europa',
      'cat_americas': 'Amerika & Andere',
      'cat_aggregator': 'Aggregatoren & Indizes',
      'retry_btn': 'Wiederholen',
      'date_today': 'Heute',
      'date_yesterday': 'Gestern',
      'rule_copied': 'Regel-JSON in Zwischenablage kopiert',
      'format_error_json': 'Formatfehler in der JSON-Sicherungsdatei.',
      'rearm_now_btn': 'Jetzt scharfstellen',
      'rearm_dialog_title': 'Alarm jetzt erneut scharfstellen?',
      'rearm_dialog_body': 'Dadurch wird die Abklingzeit sofort beendet und die Echtzeitüberwachung wieder aktiviert.',
      'alert_rule_duplicated': 'Alarmregel erfolgreich dupliziert',
      'export_rule_action': 'Regel exportieren (JSON)',
      'popular_cryptos': 'Beliebte Kryptowährungen:',
    },

    // 7. SPANISH (Español - LTR)
    'es': {
      'my_alerts': 'Mis Alertas',
      'history': 'Historial',
      'settings': 'Ajustes',
      'smart_alerts_desc': 'Monitoreo inteligente según horario personalizado',
      'new_alert': 'Añadir Nueva Alerta',
      'last_checked_price': 'Último Precio Verificado:',
      'check_now': 'Verificar Ahora',
      'baseline': 'Base',
      'rearm': 'Reactivar Alerta',
      'theme_and_colors': 'Tema y Colores',
      'theme_dark_green': 'Esmeralda Oscuro (Predeterminado)',
      'theme_light_green': 'Esmeralda Claro',
      'theme_dark_orange': 'Naranja Oscuro',
      'theme_light_orange': 'Naranja Claro',
      'theme_dark_purple_blue': 'Púrpura Azul Oscuro',
      'theme_light_purple_blue': 'Púrpura Azul Claro',
      'tts_voice_title': 'Locución de Voz Inteligente (TTS)',
      'tts_voice_desc': 'Pronuncia la moneda y el precio con voz natural al disparar la alerta',
      'tts_test_button': '🗣️ Probar Voz',
      'home_widget_title': 'Widget en Vivo de Pantalla de Inicio',
      'home_widget_desc': 'Monitoreo de alertas en vivo y proximidad al objetivo en inicio',
      'select_language': 'Idioma de la Aplicación',
      'sound_and_vibrate': 'Sonido y Vibración',
      'sound_alert': 'Sonido de Alarma',
      'vibrate_alert': 'Vibración de Alerta',
      'test_sound_button': '🔔 Probar Alarma y Notificación',
      'backup_and_restore': 'Copia de Seguridad y Restauración',
      'export_backup': 'Exportar Alertas (JSON)',
      'restore_backup': 'Restaurar Alertas (JSON)',
      'clear_history': 'Borrar Historial de Notificaciones',
      'battery_settings': 'Optimización de Batería (Android)',
      'battery_active': 'Exento de optimización (Confiable)',
      'battery_request': 'Solicitar Exención',
      'test_alert_title': 'Notificación de Prueba Alarmer',
      'test_alert_body': '¡Sonido y notificación activados con éxito en su dispositivo!',
      'backup_copied': '✅ Copia de seguridad copiada al portapapeles.',
      'restore_success': 'Alertas restauradas con éxito.',
      'exchange': 'Exchange',
      'pair': 'Par de Mercado',
      'create_alert_title': 'Crear Alerta Inteligente',
      'frequency': 'Frecuencia',
      'seconds': 'Seg',
      'minutes': 'Min',
      'hours': 'Horas',
      'empty_alerts_title': 'Aún no hay alertas configuradas',
      'empty_alerts_desc': 'Puede configurar alertas de porcentaje o precio objetivo para cripto, bonos de EE. UU. o acciones.',
      'create_first_alert': 'Crear Primera Alerta',
      'choose_market_step': 'Paso 1: Elegir Tipo de Mercado',
      'choose_market_title': '¿Qué mercado desea rastrear?',
      'choose_market_desc': 'Seleccione el mercado y activo deseado para monitorear precios con precisión.',
      'crypto_market_title': '⚡ Mercado Cripto (Criptomonedas)',
      'crypto_market_badge': '40+ Exchanges Verificados',
      'crypto_market_desc': 'Más de 40 exchanges internacionales con filtros por categoría y detección de pares.',
      'crypto_market_cta': 'Entrar a Exchanges Cripto →',
      'macro_market_title': '🏛️ Acciones de EE. UU., Bonos y Forex',
      'macro_market_badge': 'Wall Street y Macroeconomía',
      'macro_market_desc': 'Rendimientos a 10 años (US10Y), Forex, acciones Nasdaq/NYSE y Oro.',
      'macro_market_cta': 'Entrar a Mercados Globales →',
      'search_exchange_hint': 'Buscar exchange (Binance, KuCoin, Nobitex)...',
      'search_crypto_hint': 'Buscar cripto (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'Buscar símbolo (US10Y, EUR/USD, NVDA, Oro)...',
      'refresh_list': 'Actualizar Lista',
      'select_cta': 'Seleccionar →',
      'selected_asset': 'Activo Seleccionado:',
      'auto_check_schedule': '1. Horario de Verificación Automática:',
      'unit_count': 'Valor del Intervalo',
      'time_unit': 'Unidad de Tiempo',
      'condition_type': '2. Tipo de Condición de Alerta:',
      'percent_change': 'Cambio Porcentual (%)',
      'price_target': 'Precio Objetivo (\$)',
      'price_direction': 'Dirección del Precio:',
      'both_ways': '± Ambas Direcciones',
      'above_only': '▲ Solo Alza',
      'below_only': '▼ Solo Baja',
      'target_price_label': 'Precio Objetivo (\$)',
      'percent_label': 'Porcentaje Objetivo (%)',
      'save_alert_cta': 'Guardar e Iniciar Monitoreo',
      'just_now': 'Ahora mismo',
      'seconds_ago': 'hace s',
      'minutes_ago': 'hace m',
      'hours_ago': 'hace h',
      'days_ago': 'hace d',
      'every': 'Cada',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'restore_dialog_hint': 'Pegue el texto de respaldo JSON en el cuadro:',
      'restore_dialog_btn': 'Confirmar y Restaurar',
      'clear_history_confirm': '¿Seguro que desea borrar todo el historial?',
      'clear_history_btn': 'Borrar Todo',
      'clear_history_success': 'Historial de notificaciones borrado con éxito.',
      'battery_exempt_active': 'Activo (Las alertas se ejecutan puntualmente)',
      'battery_exempt_inactive': 'Inactivo (El sistema puede pausar tareas)',
      'battery_exempt_title': 'Exención de Batería',
      'battery_exempt_success': 'Exención de batería otorgada correctamente.',
      'export_backup_desc': 'Exportar todas las alertas activas en JSON',
      'restore_backup_desc': 'Restaurar alertas desde texto JSON',
      'clear_history_desc': 'Eliminar registros guardados',
      'filter_all': 'Todos',
      'filter_triggered': 'Activadas',
      'filter_suppressed': 'Suprimidas',
      'no_history_title': 'Aún No Hay Historial',
      'no_history_desc': 'Cuando se cumplan las alertas de precio, los eventos aparecerán aquí.',
      'check_price_done': 'Verificación de precio completada: ',
      'alert_deleted_msg': 'Alerta eliminada: ',
      'undo_action': 'Deshacer',
      'target_price_required': 'Por favor ingrese un precio objetivo',
      'all_symbols': 'Todos los Activos',
      'us_bonds': '🏛️ Bonos del Tesoro de EE. UU.',
      'forex_pairs': '💱 Pares de Forex',
      'gold_metals': '🥇 Oro y Metales',
      'wallstreet_stocks': '📈 Acciones de Wall Street',
      'global_indices': '🌐 Índices Globales',
      'price_cross_above': 'Cruza por encima (▲)',
      'price_cross_below': 'Cae por debajo (▼)',
      'price_cross_direction': 'Dirección del Cruce:',
      'above_target': '▲ Por Encima del Objetivo',
      'below_target': '▼ Por Debajo del Objetivo',
      'price_fluctuation': 'Cambio de precio:',
      'price_surge': 'Aumento de precio:',
      'price_drop': 'Caída de precio:',
      'target_price_summary': 'Precio objetivo:',
      'price_delta_summary': 'Delta de precio:',
      'volume_surge_summary': 'Aumento de volumen:',
      'interval_prefix': '⏱️ La verificación de precio se ejecuta cada ',
      'interval_suffix': ' en segundo plano.',
      'offline_error': 'Sin conexión a internet. Se mantiene el último precio auténtico.',
      'offline_badge': 'Desconectado',
      'edit_alert_title': 'Editar Alerta de Precio',
      'save_changes_cta': 'Guardar Cambios',
      'sound_and_vibrate_section': '3. Sonido, Vibración y Mensaje Personalizado:',
      'sound_and_vibrate_sub': 'Personalice el comportamiento de alerta para esta condición',
      'custom_note_title': 'Mensaje / Nota Personalizada de Alerta',
      'custom_note_hint': 'Ej: ¡Objetivo 1 alcanzado - Tomar 50% de ganancias!',
      'alarm_sound_title': 'Tono de Alarma para Esta Alerta',
      'change_sound_btn': 'Cambiar Tono',
      'play_sound_label': 'Reproducir Sonido',
      'vibrate_phone_label': 'Vibrar Teléfono',
      'select_alarm_sound': 'Seleccionar Tono de Alerta',
      'confirm_sound_btn': 'Confirmar y Guardar Tono',
      'live_market_price': 'Precio de Mercado en Vivo:',
      'fetching_live_price': 'Obteniendo precio en vivo...',
      'live_price_unavailable': 'Precio en vivo no disponible',
      'manual_monitoring': 'Monitoreo Manual',
      'symbol_not_found': 'No se encontraron símbolos',
      'triggers_count': 'Activaciones:',
      'last_trigger': 'Última:',
      'trigger_price_label': 'Precio de Activación:',
      'duplicate_action': 'Duplicar',
      'edit_action': 'Editar',
      'delete_action': 'Eliminar',
      'cooldown_active': 'Tiempo de Enfriamiento (Cooldown)',
      'alarm_volume_label': 'Volumen de Alarma',
      'selected_sound_label': 'Tono de Alarma Seleccionado',
      'sound_alarm_siren_title': '🚨 Sirena de Emergencia (Siren)',
      'sound_radar_pulse_title': '📡 Pulso de Radar Objetivo (Radar)',
      'sound_cyber_chime_title': '⚡ Sonido Cibernético de Trading (Cyber)',
      'sound_crystal_ping_title': '💎 Ping Cristalino (Crystal)',
      'sound_bullish_rise_title': '📈 Impulso Alcista (Ascend)',
      'sound_coin_drop_title': '🪙 Caída de Moneda Digital (Coin)',
      'sound_alert_horn_title': '🎺 Bocina de Advertencia (Horn)',
      'sound_classic_beep_title': '📟 Beep Clásico de Exchange (Beep)',
      'cat_all_exchanges': 'Todos los Exchanges',
      'cat_tier1': 'Tier-1 Global',
      'cat_middle_east': 'Oriente Medio e Irán',
      'cat_asia': 'Asia y Lejano Oriente',
      'cat_europe': 'Europa',
      'cat_americas': 'América y Otros',
      'cat_aggregator': 'Agregadores e Índices',
      'retry_btn': 'Reintentar',
      'date_today': 'Hoy',
      'date_yesterday': 'Ayer',
      'rule_copied': 'JSON de regla copiado al portapapeles',
      'format_error_json': 'Error de formato en el archivo JSON.',
      'rearm_now_btn': 'Reactivar Ahora',
      'rearm_dialog_title': '¿Reactivar alerta ahora?',
      'rearm_dialog_body': 'Esto finalizará inmediatamente el enfriamiento y reactivará el monitoreo.',
      'alert_rule_duplicated': 'Regla de alerta duplicada con éxito',
      'export_rule_action': 'Exportar Regla (JSON)',
      'popular_cryptos': 'Criptomonedas Populares:',
    },

    // 8. FRENCH (Français - LTR)
    'fr': {
      'my_alerts': 'Mes Alertes',
      'history': 'Historique',
      'settings': 'Paramètres',
      'smart_alerts_desc': 'Surveillance intelligente selon horaire personnalisé',
      'new_alert': 'Ajouter une Alerte',
      'last_checked_price': 'Dernier Prix Vérifié:',
      'check_now': 'Vérifier Maintenant',
      'baseline': 'Base',
      'rearm': 'Réarmer l\'Alerte',
      'theme_and_colors': 'Thème et Couleurs',
      'theme_dark_green': 'Émeraude Sombre (Défaut)',
      'theme_light_green': 'Émeraude Clair',
      'theme_dark_orange': 'Orange Sombre',
      'theme_light_orange': 'Orange Clair',
      'theme_dark_purple_blue': 'Violet Bleu Sombre',
      'theme_light_purple_blue': 'Violet Bleu Clair',
      'tts_voice_title': 'Annonceur Vocal Intelligent (TTS)',
      'tts_voice_desc': 'Prononce la devise et le cours avec une voix naturelle lors de l\'alerte',
      'tts_test_button': '🗣️ Tester la Voix',
      'home_widget_title': 'Widget Écran d\'Accueil en Direct',
      'home_widget_desc': 'Surveillance en direct des alertes et distance à la cible sur l\'accueil',
      'select_language': 'Langue de l\'Application',
      'sound_and_vibrate': 'Son et Vibration',
      'sound_alert': 'Sonnerie d\'Alarme',
      'vibrate_alert': 'Vibration d\'Alerte',
      'test_sound_button': '🔔 Tester Alarme et Notification',
      'backup_and_restore': 'Sauvegarde et Restauration',
      'export_backup': 'Exporter les Alertes (JSON)',
      'restore_backup': 'Restaurer les Alertes (JSON)',
      'clear_history': 'Effacer l\'Historique des Notifications',
      'battery_settings': 'Optimisation de la Batterie (Android)',
      'battery_active': 'Exempté d\'optimisation de batterie',
      'battery_request': 'Demander l\'Exemption',
      'test_alert_title': 'Notification de Test Alarmer',
      'test_alert_body': 'Son et notification déclenchés avec succès sur votre appareil !',
      'backup_copied': '✅ Sauvegarde copiée dans le presse-papiers.',
      'restore_success': 'Alertes restaurées avec succès.',
      'exchange': 'Plateforme',
      'pair': 'Paire de Marché',
      'create_alert_title': 'Créer une Alerte Intelligente',
      'frequency': 'Fréquence',
      'seconds': 'Sec',
      'minutes': 'Min',
      'hours': 'Heures',
      'empty_alerts_title': 'Aucune Alerte Configurée',
      'empty_alerts_desc': 'Configurez des alertes de pourcentage ou de prix cible pour crypto, obligations US ou actions.',
      'create_first_alert': 'Créer une Première Alerte',
      'choose_market_step': 'Étape 1: Choisir le Marché',
      'choose_market_title': 'Quel marché souhaitez-vous suivre ?',
      'choose_market_desc': 'Sélectionnez le marché et l\'actif pour surveiller les prix avec précision.',
      'crypto_market_title': '⚡ Marché Crypto (Cryptomonnaies)',
      'crypto_market_badge': 'Plus de 40 Plateformes Vérifiées',
      'crypto_market_desc': 'Plus de 40 plateformes internationales avec filtres et détection automatique.',
      'crypto_market_cta': 'Entrer dans les Plateformes Crypto →',
      'macro_market_title': '🏛️ Actions US, Obligations & Forex',
      'macro_market_badge': 'Wall Street et Macroéconomie',
      'macro_market_desc': 'Rendements 10 ans US (US10Y), Forex, actions Nasdaq/NYSE et Or.',
      'macro_market_cta': 'Entrer dans les Marchés Globaux →',
      'search_exchange_hint': 'Rechercher plateforme (Binance, KuCoin)...',
      'search_crypto_hint': 'Rechercher crypto (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'Rechercher symbole (US10Y, EUR/USD, Or)...',
      'refresh_list': 'Actualiser la Liste',
      'select_cta': 'Sélectionner →',
      'selected_asset': 'Actif Sélectionné:',
      'auto_check_schedule': '1. Calendrier de Vérification:',
      'unit_count': 'Valeur d\'Intervalle',
      'time_unit': 'Unité de Temps',
      'condition_type': '2. Type de Condition d\'Alerte:',
      'percent_change': 'Changement de Pourcentage (%)',
      'price_target': 'Prix Cible (\$)',
      'price_direction': 'Direction du Prix:',
      'both_ways': '± Les Deux Sens',
      'above_only': '▲ Hausse Uniquement',
      'below_only': '▼ Baisse Uniquement',
      'target_price_label': 'Prix Cible (\$)',
      'percent_label': 'Pourcentage Cible (%)',
      'save_alert_cta': 'Enregistrer et Surveiller',
      'just_now': 'À l\'instant',
      'seconds_ago': 'il y a s',
      'minutes_ago': 'il y a m',
      'hours_ago': 'il y a h',
      'days_ago': 'il y a j',
      'every': 'Chaque',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'restore_dialog_hint': 'Collez le texte JSON de sauvegarde ci-dessous:',
      'restore_dialog_btn': 'Confirmer et Restaurer',
      'clear_history_confirm': 'Voulez-vous vraiment effacer tout l\'historique ?',
      'clear_history_btn': 'Tout Effacer',
      'clear_history_success': 'Historique des notifications effacé.',
      'battery_exempt_active': 'Actif (Les alertes fonctionnent à l\'heure)',
      'battery_exempt_inactive': 'Inactif (Les tâches peuvent être suspendues)',
      'battery_exempt_title': 'Exemption de Batterie',
      'battery_exempt_success': 'Exemption accordée avec succès.',
      'export_backup_desc': 'Exporter toutes les alertes en JSON',
      'restore_backup_desc': 'Restaurer les alertes depuis le texte JSON',
      'clear_history_desc': 'Supprimer tous les journaux enregistrés',
      'filter_all': 'Tous',
      'filter_triggered': 'Déclenchées',
      'filter_suppressed': 'Supprimées',
      'no_history_title': 'Aucun Historique',
      'no_history_desc': 'Lorsque les conditions d\'alerte sont atteintes, les événements apparaissent ici.',
      'check_price_done': 'Vérification du prix effectuée: ',
      'alert_deleted_msg': 'Alerte supprimée: ',
      'undo_action': 'Annuler',
      'target_price_required': 'Veuillez saisir un prix cible',
      'all_symbols': 'Tous les Actifs',
      'us_bonds': '🏛️ Obligations du Trésor US',
      'forex_pairs': '💱 Paires Forex',
      'gold_metals': '🥇 Or et Métaux',
      'wallstreet_stocks': '📈 Actions Wall Street',
      'global_indices': '🌐 Indices Globaux',
      'price_cross_above': 'Dépasse par le haut (▲)',
      'price_cross_below': 'Passe en dessous (▼)',
      'price_cross_direction': 'Sens du Croisement:',
      'above_target': '▲ Au-dessus de la Cible',
      'below_target': '▼ En-dessous de la Cible',
      'price_fluctuation': 'Changement de prix:',
      'price_surge': 'Hausse de prix:',
      'price_drop': 'Baisse de prix:',
      'target_price_summary': 'Prix cible:',
      'price_delta_summary': 'Delta de prix:',
      'volume_surge_summary': 'Hausse de volume:',
      'interval_prefix': '⏱️ La vérification de prix s\'exécute toutes les ',
      'interval_suffix': ' en arrière-plan.',
      'offline_error': 'Pas de connexion Internet. Dernier prix authentique conservé.',
      'offline_badge': 'Hors ligne',
      'edit_alert_title': 'Modifier l\'Alerte',
      'save_changes_cta': 'Enregistrer les Modifications',
      'sound_and_vibrate_section': '3. Son, Vibration & Note Personnalisée:',
      'sound_and_vibrate_sub': 'Personnalisez le comportement de l\'alerte pour cette condition',
      'custom_note_title': 'Message / Note d\'Alerte Personnalisée',
      'custom_note_hint': 'Ex: Objectif 1 atteint - Prendre 50% de bénéfices !',
      'alarm_sound_title': 'Sonnerie de Cette Alerte',
      'change_sound_btn': 'Changer le Son',
      'play_sound_label': 'Jouer le Son',
      'vibrate_phone_label': 'Faire Vibrer le Téléphone',
      'select_alarm_sound': 'Sélectionner la Sonnerie',
      'confirm_sound_btn': 'Confirmer & Enregistrer',
      'live_market_price': 'Prix du Marché en Direct:',
      'fetching_live_price': 'Récupération du prix en direct...',
      'live_price_unavailable': 'Prix en direct indisponible',
      'manual_monitoring': 'Surveillance Manuelle',
      'symbol_not_found': 'Aucun symbole trouvé',
      'triggers_count': 'Déclenchements:',
      'last_trigger': 'Dernier:',
      'trigger_price_label': 'Prix de Déclenchement:',
      'duplicate_action': 'Dupliquer',
      'edit_action': 'Modifier',
      'delete_action': 'Supprimer',
      'cooldown_active': 'Période de Refroidissement (Cooldown)',
      'alarm_volume_label': 'Volume de l\'Alarme',
      'selected_sound_label': 'Sonnerie d\'Alarme Sélectionnée',
      'sound_alarm_siren_title': '🚨 Sirène d\'Urgence (Siren)',
      'sound_radar_pulse_title': '📡 Impulsion Radar Cible (Radar)',
      'sound_cyber_chime_title': '⚡ Carillon de Trading Cyber (Cyber)',
      'sound_crystal_ping_title': '💎 Ping Cristallin (Crystal)',
      'sound_bullish_rise_title': '📈 Poussée Haussière (Ascend)',
      'sound_coin_drop_title': '🪙 Chute de Pièces Numériques (Coin)',
      'sound_alert_horn_title': '🎺 Corne d\'Avertissement Marché (Horn)',
      'sound_classic_beep_title': '📟 Bip Classique de Bourse (Beep)',
      'cat_all_exchanges': 'Tous les Exchanges',
      'cat_tier1': 'Tier-1 Global',
      'cat_middle_east': 'Moyen-Orient & Iran',
      'cat_asia': 'Asie & Extrême-Orient',
      'cat_europe': 'Europe',
      'cat_americas': 'Amériques & Autres',
      'cat_aggregator': 'Agrégateurs & Indices',
      'retry_btn': 'Réessayer',
      'date_today': 'Aujourd\'hui',
      'date_yesterday': 'Hier',
      'rule_copied': 'JSON de règle copié dans le presse-papiers',
      'format_error_json': 'Erreur de format dans le fichier JSON.',
      'rearm_now_btn': 'Réarmer Maintenant',
      'rearm_dialog_title': 'Réarmer l\'alerte maintenant ?',
      'rearm_dialog_body': 'Cela mettra fin immédiatement à la période d\'attente et réactivera la surveillance.',
      'alert_rule_duplicated': 'Règle d\'alerte dupliquée avec succès',
      'export_rule_action': 'Exporter la Règle (JSON)',
      'popular_cryptos': 'Cryptomonnaies Populaires :',
    },

    // 9. RUSSIAN (Русский - LTR)
    'ru': {
      'my_alerts': 'Мои Оповещения',
      'history': 'История',
      'settings': 'Настройки',
      'smart_alerts_desc': 'Умный мониторинг цен по индивидуальному расписанию',
      'new_alert': 'Добавить Оповещение',
      'last_checked_price': 'Последняя Проверенная Цена:',
      'check_now': 'Проверить Сейчас',
      'baseline': 'База',
      'rearm': 'Перезапустить',
      'theme_and_colors': 'Тема и Цвета',
      'theme_dark_green': 'Тёмно-Изумрудный (По умолчанию)',
      'theme_light_green': 'Светло-Изумрудный',
      'theme_dark_orange': 'Тёмно-Оранжевый',
      'theme_light_orange': 'Светло-Оранжевый',
      'theme_dark_purple_blue': 'Тёмно-Фиолетово-Синий',
      'theme_light_purple_blue': 'Светло-Фиолетово-Синий',
      'tts_voice_title': 'Голосовое Оповещение (Text-to-Speech)',
      'tts_voice_desc': 'Произносит название актива и цену голосом при срабатывании сигнала',
      'tts_test_button': '🗣️ Тест Голоса',
      'home_widget_title': 'Виджет Главного Экрана',
      'home_widget_desc': 'Мониторинг алертов и близости к цели прямо на главном экране',
      'select_language': 'Язык Приложения',
      'sound_and_vibrate': 'Звук и Вибрация',
      'sound_alert': 'Звук Сигнала',
      'vibrate_alert': 'Вибрация при Сигнале',
      'test_sound_button': '🔔 Тест Звука и Уведомления',
      'backup_and_restore': 'Резервное Копирование и Восстановление',
      'export_backup': 'Экспорт Оповещений (JSON)',
      'restore_backup': 'Восстановление Оповещений (JSON)',
      'clear_history': 'Очистить Историю Уведомлений',
      'battery_settings': 'Оптимизация Батареи (Android)',
      'battery_active': 'Исключено из оптимизации (Надёжно)',
      'battery_request': 'Запросить Исключение',
      'test_alert_title': 'Тестовое Уведомление Alarmer',
      'test_alert_body': 'Звук и уведомление успешно сработали на вашем устройстве!',
      'backup_copied': '✅ Резервная копия скопирована в буфер обмена.',
      'restore_success': 'Оповещения успешно восстановлены.',
      'exchange': 'Биржа',
      'pair': 'Торговая Пара',
      'create_alert_title': 'Создать Умное Оповещение',
      'frequency': 'Частота Проверки',
      'seconds': 'Сек',
      'minutes': 'Мин',
      'hours': 'Час',
      'empty_alerts_title': 'Оповещения Пока Не Настроены',
      'empty_alerts_desc': 'Вы можете настроить оповещения по процентному изменению или целевой цене для криптовалют, облигаций США или акций.',
      'create_first_alert': 'Создать Первое Оповещение',
      'choose_market_step': 'Шаг 1: Выбор Рынка',
      'choose_market_title': 'Какой рынок вы хотите отслеживать?',
      'choose_market_desc': 'Выберите рынок и актив для точного мониторинга цен.',
      'crypto_market_title': '⚡ Криптовалютный Рынок',
      'crypto_market_badge': 'Более 40 Проверенных Бирж',
      'crypto_market_desc': 'Более 40 международных бирж с фильтрами и автопоиском пар.',
      'crypto_market_cta': 'Перейти к Криптобиржам →',
      'macro_market_title': '🏛️ Акции США, Облигации и Форекс',
      'macro_market_badge': 'Уолл-стрит и Макроэкономика',
      'macro_market_desc': '10-летние облигации США (US10Y), Форекс, акции Nasdaq/NYSE и Золото.',
      'macro_market_cta': 'Перейти к Мировым Рынкам →',
      'search_exchange_hint': 'Поиск биржи (Binance, KuCoin)...',
      'search_crypto_hint': 'Поиск крипто (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'Поиск символа (US10Y, EUR/USD, Золото)...',
      'refresh_list': 'Обновить Список',
      'select_cta': 'Выбрать →',
      'selected_asset': 'Выбранный Актив:',
      'auto_check_schedule': '1. Расписание Автопроверки:',
      'unit_count': 'Значение Интервала',
      'time_unit': 'Единица Времени',
      'condition_type': '2. Тип Условия Оповещения:',
      'percent_change': 'Процентное Изменение (%)',
      'price_target': 'Целевая Цена (\$)',
      'price_direction': 'Направление Цены:',
      'both_ways': '± В Обе Стороны',
      'above_only': '▲ Только Рост',
      'below_only': '▼ Только Падение',
      'target_price_label': 'Целевая Цена (\$)',
      'percent_label': 'Целевой Процент (%)',
      'save_alert_cta': 'Сохранить и Начать Мониторинг',
      'just_now': 'Только что',
      'seconds_ago': 'сек назад',
      'minutes_ago': 'мин назад',
      'hours_ago': 'ч назад',
      'days_ago': 'дн назад',
      'every': 'Каждые',
      'cancel': 'Отмена',
      'confirm': 'Подтвердить',
      'restore_dialog_hint': 'Вставьте текст резервной копии JSON в поле ниже:',
      'restore_dialog_btn': 'Подтвердить и Восстановить',
      'clear_history_confirm': 'Вы уверены, что хотите удалить всю историю уведомлений?',
      'clear_history_btn': 'Очистить Всё',
      'clear_history_success': 'История уведомлений очищена.',
      'battery_exempt_active': 'Активно (Оповещения срабатывают точно вовремя)',
      'battery_exempt_inactive': 'Неактивно (Фоновые проверки могут приостанавливаться)',
      'battery_exempt_title': 'Исключение из Оптимизации Батареи',
      'battery_exempt_success': 'Исключение успешно предоставлено.',
      'export_backup_desc': 'Экспортировать все активные оповещения в JSON',
      'restore_backup_desc': 'Импортировать оповещения из текста JSON',
      'clear_history_desc': 'Удалить все сохраненные логи и уведомления',
      'filter_all': 'Все',
      'filter_triggered': 'Сработавшие',
      'filter_suppressed': 'Подавленные',
      'no_history_title': 'История Пока Пуста',
      'no_history_desc': 'При срабатывании условий оповещений события будут отображаться здесь.',
      'check_price_done': 'Проверка цены выполнена: ',
      'alert_deleted_msg': 'Оповещение удалено: ',
      'undo_action': 'Отменить',
      'target_price_required': 'Пожалуйста, введите целевую цену',
      'all_symbols': 'Все Активы',
      'us_bonds': '🏛️ Казначейские Облигации США',
      'forex_pairs': '💱 Пары Форекс',
      'gold_metals': '🥇 Золото и Металлы',
      'wallstreet_stocks': '📈 Акции Уолл-стрит',
      'global_indices': '🌐 Мировые Индексы',
      'price_cross_above': 'Пересекает снизу вверх (▲)',
      'price_cross_below': 'Опускается ниже (▼)',
      'price_cross_direction': 'Направление Пересечения:',
      'above_target': '▲ Выше Цели',
      'below_target': '▼ Ниже Цели',
      'price_fluctuation': 'Изменение цены:',
      'price_surge': 'Рост цены:',
      'price_drop': 'Падение цены:',
      'target_price_summary': 'Целевая цена:',
      'price_delta_summary': 'Дельта цены:',
      'volume_surge_summary': 'Всплеск объема:',
      'interval_prefix': '⏱️ Проверка цены выполняется каждые ',
      'interval_suffix': ' в фоновом режиме.',
      'offline_error': 'Нет подключения к интернету. Сохранена последняя актуальная цена.',
      'offline_badge': 'Офлайн',
      'edit_alert_title': 'Редактировать Оповещение',
      'save_changes_cta': 'Сохранить Изменения',
      'sound_and_vibrate_section': '3. Настройки Звука, Вибрации и Заметки:',
      'sound_and_vibrate_sub': 'Настройте поведение оповещения для этого условия',
      'custom_note_title': 'Личное Сообщение / Заметка к Сигналу',
      'custom_note_hint': 'Например: Цель 1 достигнута - зафиксируйте 50% прибыли!',
      'alarm_sound_title': 'Мелодия для Этого Оповещения',
      'change_sound_btn': 'Изменить Звук',
      'play_sound_label': 'Воспроизвести',
      'vibrate_phone_label': 'Вибрация Телефона',
      'select_alarm_sound': 'Выбрать Звук Оповещения',
      'confirm_sound_btn': 'Подтвердить и Сохранить Звук',
      'live_market_price': 'Текущая Рыночная Цена:',
      'fetching_live_price': 'Получение текущей цены...',
      'live_price_unavailable': 'Текущая цена недоступна',
      'manual_monitoring': 'Ручной Мониторинг',
      'symbol_not_found': 'Символы не найдены',
      'triggers_count': 'Срабатываний:',
      'last_trigger': 'Последнее:',
      'trigger_price_label': 'Цена Срабатывания:',
      'duplicate_action': 'Дублировать',
      'edit_action': 'Редактировать',
      'delete_action': 'Удалить',
      'cooldown_active': 'Время Отдыха (Cooldown)',
      'alarm_volume_label': 'Громкость Сигнала',
      'selected_sound_label': 'Выбранный Звук Сигнала',
      'sound_alarm_siren_title': '🚨 Аварийная Сирена (Siren)',
      'sound_radar_pulse_title': '📡 Импульс Радара Цели (Radar)',
      'sound_cyber_chime_title': '⚡ Кибернетический Звонок (Cyber)',
      'sound_crystal_ping_title': '💎 Хрустальный Пинг (Crystal)',
      'sound_bullish_rise_title': '📈 Бычий Импульс Роста (Ascend)',
      'sound_coin_drop_title': '🪙 Звон Цифровой Монеты (Coin)',
      'sound_alert_horn_title': '🎺 Сигнальный Горн Рынка (Horn)',
      'sound_classic_beep_title': '📟 Классический Биржевой Бип (Beep)',
      'cat_all_exchanges': 'Все Криптобиржи',
      'cat_tier1': 'Топ-1 Биржи (Tier-1)',
      'cat_middle_east': 'Ближний Восток и Иран',
      'cat_asia': 'Азия и Дальний Восток',
      'cat_europe': 'Европа',
      'cat_americas': 'Америка и Другие',
      'cat_aggregator': 'Агрегаторы и Индексы',
      'retry_btn': 'Повторить',
      'date_today': 'Сегодня',
      'date_yesterday': 'Вчера',
      'rule_copied': 'JSON правила скопирован в буфер обмена',
      'format_error_json': 'Ошибка формата в файле резервной копии JSON.',
      'rearm_now_btn': 'Перезапустить Сейчас',
      'rearm_dialog_title': 'Перезапустить оповещение сейчас?',
      'rearm_dialog_body': 'Это немедленно завершит время отдыха и возобновит отслеживание.',
      'alert_rule_duplicated': 'Правило оповещения успешно дублировано',
      'export_rule_action': 'Экспорт Правила (JSON)',
      'popular_cryptos': 'Популярные Криптовалюты:',
    },

    // 10. CHINESE (中文 - LTR)
    'zh': {
      'my_alerts': '我的预警',
      'history': '历史记录',
      'settings': '设置',
      'smart_alerts_desc': '基于自定义时间表的智能价格监控',
      'new_alert': '添加新预警',
      'last_checked_price': '最后检测价格：',
      'check_now': '立即检查',
      'baseline': '基准',
      'rearm': '重新启用',
      'theme_and_colors': '主题与配色',
      'theme_dark_green': '深翡翠绿（默认）',
      'theme_light_green': '浅翡翠绿',
      'theme_dark_orange': '深橙色',
      'theme_light_orange': '浅橙色',
      'theme_dark_purple_blue': '深紫蓝色',
      'theme_light_purple_blue': '浅紫蓝色',
      'tts_voice_title': '智能语音播报（Text-to-Speech）',
      'tts_voice_desc': '警报触发时通过自然语音朗读币种名称与实时价格',
      'tts_test_button': '🗣️ 测试语音播报',
      'home_widget_title': '主屏幕实时小组件（Widget）',
      'home_widget_desc': '在手机桌面上实时监控预警状态及目标接近进度',
      'select_language': '应用语言',
      'sound_and_vibrate': '声音与震动',
      'sound_alert': '报警声音',
      'vibrate_alert': '预警震动',
      'test_sound_button': '🔔 测试报警声音与通知',
      'backup_and_restore': '备份与恢复',
      'export_backup': '导出预警规则 (JSON)',
      'restore_backup': '恢复预警规则 (JSON)',
      'clear_history': '清空通知历史记录',
      'battery_settings': '后台电池优化 (Android)',
      'battery_active': '已豁免电池优化限制（可靠运行）',
      'battery_request': '申请电池优化豁免',
      'test_alert_title': 'Alarmer 测试通知',
      'test_alert_body': '声音和通知已在您的设备上成功触发！',
      'backup_copied': '✅ 备份已成功复制到剪贴板。',
      'restore_success': '预警规则已成功恢复。',
      'exchange': '交易所',
      'pair': '交易对',
      'create_alert_title': '创建智能预警',
      'frequency': '检测频率',
      'seconds': '秒',
      'minutes': '分钟',
      'hours': '小时',
      'empty_alerts_title': '尚未配置任何预警',
      'empty_alerts_desc': '您可以为加密货币、美债收益率或全球股票设置涨跌幅及目标价预警。',
      'create_first_alert': '创建第一个智能预警',
      'choose_market_step': '步骤 1：选择市场类型',
      'choose_market_title': '您希望监控哪个市场？',
      'choose_market_desc': '选择您要追踪的市场类型和资产，以准确监控价格变动。',
      'crypto_market_title': '⚡ 加密货币市场 (Crypto)',
      'crypto_market_badge': '40+ 家认证交易所',
      'crypto_market_desc': '支持全球40多家顶级交易所，具备分类筛选与交易对自动发现。',
      'crypto_market_cta': '进入加密货币交易所 →',
      'macro_market_title': '🏛️ 美股、美国国债与外汇',
      'macro_market_badge': '华尔街与宏观经济',
      'macro_market_desc': '美国10年期国债收益率 (US10Y)、外汇对、纳斯达克/纽交所股票及黄金。',
      'macro_market_cta': '进入全球金融市场 →',
      'search_exchange_hint': '搜索交易所 (Binance, KuCoin)...',
      'search_crypto_hint': '搜索加密货币 (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': '搜索代码 (US10Y, EUR/USD, NVDA, 黄金)...',
      'refresh_list': '刷新列表',
      'select_cta': '选择 →',
      'selected_asset': '已选资产：',
      'auto_check_schedule': '1. 自动检查时间表：',
      'unit_count': '间隔数值',
      'time_unit': '时间单位',
      'condition_type': '2. 预警触发条件类型：',
      'percent_change': '百分比涨跌幅 (%)',
      'price_target': '目标价格 (\$)',
      'price_direction': '价格波动方向：',
      'both_ways': '± 双向波动',
      'above_only': '▲ 仅上涨突破',
      'below_only': '▼ 仅下跌跌破',
      'target_price_label': '目标价格（美元）',
      'percent_label': '目标涨跌百分比 (%)',
      'save_alert_cta': '保存并启动监控',
      'just_now': '刚刚',
      'seconds_ago': '秒前',
      'minutes_ago': '分钟前',
      'hours_ago': '小时前',
      'days_ago': '天前',
      'every': '每',
      'cancel': '取消',
      'confirm': '确认',
      'restore_dialog_hint': '请将导出的 JSON 备份文本粘贴到下方框中：',
      'restore_dialog_btn': '确认并恢复',
      'clear_history_confirm': '您确定要清空所有通知历史记录吗？',
      'clear_history_btn': '全部清空',
      'clear_history_success': '通知历史记录已清空。',
      'battery_exempt_active': '已启用（预警将在后台准时运行）',
      'battery_exempt_inactive': '未启用（系统可能会暂停后台任务）',
      'battery_exempt_title': '电池优化豁免',
      'battery_exempt_success': '电池优化豁免已成功获得。',
      'export_backup_desc': '将所有活跃的预警导出为 JSON 文件',
      'restore_backup_desc': '从 JSON 文本导入并恢复预警',
      'clear_history_desc': '删除所有已保存的历史日志和通知',
      'filter_all': '全部',
      'filter_triggered': '已触发',
      'filter_suppressed': '已抑制',
      'no_history_title': '暂无历史记录',
      'no_history_desc': '当满足价格预警条件时，事件记录将显示在这里。',
      'check_price_done': '价格检查已完成：',
      'alert_deleted_msg': '预警已删除：',
      'undo_action': '撤销',
      'target_price_required': '请输入目标价格',
      'all_symbols': '全部资产',
      'us_bonds': '🏛️ 美国国债收益率',
      'forex_pairs': '💱 外汇货币对',
      'gold_metals': '🥇 黄金与贵金属',
      'wallstreet_stocks': '📈 华尔街美股',
      'global_indices': '🌐 全球股指',
      'price_cross_above': '向上突破 (▲)',
      'price_cross_below': '向下跌破 (▼)',
      'price_cross_direction': '突破方向：',
      'above_target': '▲ 高于目标价',
      'below_target': '▼ 低于目标价',
      'price_fluctuation': '价格变动：',
      'price_surge': '价格上涨：',
      'price_drop': '价格下跌：',
      'target_price_summary': '目标价：',
      'price_delta_summary': '价格差额：',
      'volume_surge_summary': '成交量突增：',
      'interval_prefix': '⏱️ 价格自动检查将在后台每 ',
      'interval_suffix': ' 执行一次。',
      'offline_error': '无网络连接。保留上次获取的真实价格。',
      'offline_badge': '离线',
      'edit_alert_title': '编辑价格预警',
      'save_changes_cta': '保存修改',
      'sound_and_vibrate_section': '3. 声音、震动及自定义附言设置：',
      'sound_and_vibrate_sub': '为此特定条件定制预警通知行为',
      'custom_note_title': '自定义预警提示附言 / 交易笔记',
      'custom_note_hint': '例如：止盈目标1已达成 - 减仓50%利润！',
      'alarm_sound_title': '此预警专用铃声',
      'change_sound_btn': '更改铃声',
      'play_sound_label': '播放声音',
      'vibrate_phone_label': '手机震动',
      'select_alarm_sound': '选择预警铃声',
      'confirm_sound_btn': '确认并保存铃声',
      'live_market_price': '实时市场价格：',
      'fetching_live_price': '正在获取实时价格...',
      'live_price_unavailable': '实时价格不可用',
      'manual_monitoring': '手动监控',
      'symbol_not_found': '未找到匹配的代码',
      'triggers_count': '触发次数：',
      'last_trigger': '上次：',
      'trigger_price_label': '触发价格：',
      'duplicate_action': '复制',
      'edit_action': '编辑',
      'delete_action': '删除',
      'cooldown_active': '冷却时间 (Cooldown)',
      'alarm_volume_label': '报警音量',
      'selected_sound_label': '已选报警铃声',
      'sound_alarm_siren_title': '🚨 紧急突发警报 (Siren)',
      'sound_radar_pulse_title': '📡 雷达目标脉冲 (Radar)',
      'sound_cyber_chime_title': '⚡ 赛博交易提示音 (Cyber)',
      'sound_crystal_ping_title': '💎 清脆水晶提示音 (Crystal)',
      'sound_bullish_rise_title': '📈 多头暴涨提示 (Ascend)',
      'sound_coin_drop_title': '🪙 数字硬币声 (Coin)',
      'sound_alert_horn_title': '🎺 市场警示号角 (Horn)',
      'sound_classic_beep_title': '📟 交易所经典哔哔声 (Beep)',
      'cat_all_exchanges': '全部加密货币交易所',
      'cat_tier1': '全球顶级 (Tier-1)',
      'cat_middle_east': '中东与伊朗',
      'cat_asia': '亚洲与远东',
      'cat_europe': '欧洲',
      'cat_americas': '美洲及其它',
      'cat_aggregator': '聚合平台与指数',
      'retry_btn': '重试',
      'date_today': '今天',
      'date_yesterday': '昨天',
      'rule_copied': '规则 JSON 已复制到剪贴板',
      'format_error_json': 'JSON 备份文件格式错误。',
      'rearm_now_btn': '立即重新启用',
      'rearm_dialog_title': '立即重新启用预警？',
      'rearm_dialog_body': '这将立即结束冷却期并重新恢复实时触发监控。',
      'alert_rule_duplicated': '预警规则已成功复制',
      'export_rule_action': '导出规则 (JSON)',
      'popular_cryptos': '热门加密货币：',
    },
  };

  /// Returns localized string by [key] for selected [lang]. Fallbacks cleanly to English.
  static String get(String key, String lang) {
    final map = _translations[lang] ?? _translations['en']!;
    return map[key] ?? _translations['en']?[key] ?? key;
  }
}
